[WIP] feat(data-viz): add color palette component
carbon-design-system/carbon-website pull request #1407
Opened 2020-07-22 01:09 UTC by jnm2377

Closes https://github.com/carbon-design-system/design-language-website/issues/564

Adds `ColorPalette` component to data viz colors pages. 

### To-do:
- [ ] fix style bugs
    - [ ] palette colors borders 
    - [ ] switcher styles (had to override carbon switcher styles to look like design)
    - [ ] palette controls borders (dropdown/switcher where it touches colors)
- [ ] fix dropdown selection bug (not showing highlight when selection changes)
- [ ] add alert colors palette

2020-07-22 01:13 UTC, jnm2377 commented
@jeanservaas still working on things here, but you can start seeing the work/checking the colors are correct.

2020-07-27 20:17 UTC, jnm2377 commented
@jeanservaas I was still working on the border styling when I pushed last week. It should be updated now. It was a bit tricky bc there were a lot of nuances that borders and outlines have that weren't matching up with the spec.

2020-07-27 20:34 UTC, jnm2377 commented
@jeanservaas still need to update the sequential palette to the new design, but shouldn't take long

2020-07-27 20:38 UTC, jnm2377 commented
@jeanservaas I was gonna ask if the responsive breakpoints are correct, bc it seems like they should be changing before those breakpoints. i.e. the specs show that it'll go to one column at the `sm/320px` breakpoint, but it seems like it should happen sooner... same goes for changing from 3 to 2 columns....

2020-08-20 17:36 UTC, jeanservaas commented
@jnm2377 sorry, I can't interact with the new preview link.

2020-08-20 21:29 UTC, jeanservaas commented
@jnm2377 this looks so good and it's so close.

There is one thing I missed about component on the grid (do not hate me).

Notice to the right, how our component is on the columns, aligned with the type above it. The component on IDL hangs 16px into the gutter on the left and the right of the columns... which is how we want it.

## Comparison: Carbon (rt) / IDL (lft)

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/43144260/90826457-13ce1700-e300-11ea-9535-15976684f41f.png">

## On the plus side IT LOOKS GREAT AT MOBILE!

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/43144260/90826657-78897180-e300-11ea-8b0c-be4ff47ddc96.png">


## At tablet, you want a 16px margin on either side of component, not 32px

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/43144260/90826746-9f47a800-e300-11ea-8cc8-adff1f230012.png">


## Lrg and XL (the right side will have a 16px margin)

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/43144260/90827607-21849c00-e302-11ea-9e64-bde809c57419.png">



The only other little problem I'm having is that I can't see the gallery in my local build, but I'm sure that's a problem on my end. Maybe you could just screen grab it for me or something.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/43144260/90826939-f483b980-e300-11ea-9557-c8227504f4f8.png">

2020-09-01 15:39 UTC, vpicone commented on src/components/ColorPalette/ColorPalette.js
> +  const setFalse = () => {
Usually the `set[variable]` syntax goes with the the second return value from hooks. Here it sounds like you're setting a variable called `false` to something. When in doubt prefer long names that explain completely what's happening.

2020-09-01 15:39 UTC, vpicone commented on src/components/ColorPalette/ColorPalette.js
> +  const setTrue = () => {
Same as `setFalse` maybe we could combine these functions and pass in a variable to determine the behavior (rather than splitting in two)

2020-09-01 15:43 UTC, vpicone commented on src/components/ColorPalette/_color-palette.scss
> +// MAIN CONTAINER
In general, most of the new styles we've added with the theme use css modules. Especially for something as compartmentalized as this it not only prevents class collisions but enforces good practices for not cross-referencing styles between sheets. 

Something like `dark-mode` or `light-text` could very easily be used in a different stylesheet and we'd be impacting those styles.

2020-09-02 19:15 UTC, vpicone approved these changes

2020-09-02 19:31 UTC, theiliad commented
Thank you @jnm2377 for putting this work in! 🎉

2020-09-03 14:10 UTC, sstrubberg approved these changes

2020-09-03 15:26 UTC, theiliad requested changes
Couple of points @jeanservaas:
1. Gradients on gauge hasn't been approved (we also probably wouldn't want to recommend those)
![image](https://user-images.githubusercontent.com/14989804/92132388-17b86980-edd5-11ea-848c-f27d43ce6231.png)

2. ![image](https://user-images.githubusercontent.com/14989804/92132617-5f3ef580-edd5-11ea-80c4-c564924d676f.png)
Couple of gradients on this page we might not want to recommend
![image](https://user-images.githubusercontent.com/14989804/92135007-3c621080-edd8-11ea-8bba-43490491f1ac.png)

2020-09-03 15:58 UTC, vpicone commented
@theiliad do you mind opening a separate issue for those so we can merge this?

2020-09-03 21:41 UTC, jeanservaas commented
@theiliad yes, let's deal with this in a separate issue. I'll address both of those issues next week but I don't want to block this.

Also @jnm2377 and @vpicone Showing this preview to the design crit I noticed that 

- Color in action section needs an anchor link (my bad)

- that resources link is old, the palette is in the master charts file on the gentling start page — can you just remove the resources section entirely?

Sorry!!

2020-09-03 21:55 UTC, vpicone commented
@jnm2377 feel free to merge it after @jeanservaas's things get handled

2020-09-03 21:58 UTC, jnm2377 commented
@vpicone already pushed a fix, I can't merge tho. It won't let me.

2020-09-03 23:33 UTC, alisonjoseph approved these changes

2020-09-03 23:33 UTC, merged