Update Carbon Native Mobile links (no fathom, please add)
carbon-design-system/carbon-website pull request #1770
Opened 2020-09-17 21:08 UTC by mariuszmickiewicz

**Changed**

- Updates Carbon Native Mobile links (**no fathom, please add**)

2020-09-17 22:49 UTC, mariuszmickiewicz commented
Locally page renders ok, but in vercel's preview next section's heading shows as a pure text
### Components and pattern

2020-09-21 15:00 UTC, emyarod approved these changes

2020-09-21 16:06 UTC, andreancardona approved these changes
@mariuszmickiewicz looks good to me!

2020-09-23 15:13 UTC, jillianhowarth requested changes
@mariuszmickiewicz just a couple content tweaks to make the cards more clear, but otherwise it looks great! Let me know if you have any questions 🙂

2020-09-23 15:13 UTC, jillianhowarth commented on src/pages/whats-happening/work-in-progress/index.mdx
>  <CardGroup>
```suggestion
**React Native Sketch kits for mobile**

<CardGroup>
```

2020-09-23 15:13 UTC, jillianhowarth commented on src/pages/whats-happening/work-in-progress/index.mdx
> +    title="Carbon Native Mobile (Light theme)"
```suggestion
    title="Light theme"
```

2020-09-23 15:13 UTC, jillianhowarth commented on src/pages/whats-happening/work-in-progress/index.mdx
> +    title="Carbon Native Mobile (Dark theme)"
```suggestion
    title="Dark theme"
```

2020-09-23 15:13 UTC, jillianhowarth commented on src/pages/whats-happening/work-in-progress/index.mdx
> +    title="IBM Grid template (Native Mobile)"
```suggestion
    title="IBM Grid template"
```

2020-09-23 15:38 UTC, mariuszmickiewicz commented
@jillianhowarth Thanks for the updates!

2020-09-23 15:42 UTC, mariuszmickiewicz commented
@jillianhowarth Do you know who could help with fathom codes?

2020-09-23 18:26 UTC, joshblack commented
Just pushed up a change with the goals, hope that works @jillianhowarth @mariuszmickiewicz!

2020-09-23 19:49 UTC, mariuszmickiewicz reviewed
I can't approve this update somehow (as I'm the pull requester), but if anyone can that would be cool.

2020-09-23 20:24 UTC, jillianhowarth approved these changes
🎉

2020-09-23 20:52 UTC, merged

2020-09-28 16:56 UTC, mariuszmickiewicz commented
Hmm, this doesn't seem to be visible on the live site.

2020-09-28 18:11 UTC, janchild commented
You're right, @mariuszmickiewicz. 

@alisonjoseph Do you mind checking to see why these WIP page additions aren't showing on the site?

2020-09-28 18:33 UTC, tw15egan commented
Seems like they were accidentally removed in this PR: https://github.com/carbon-design-system/carbon-website/pull/1827/files

I'll get up a PR to fix this, @mariuszmickiewicz!