Create facet-filter-tags
carbon-design-system/carbon-website pull request #1836
Opened 2020-09-24 16:53 UTC by heatherco

Facet filters with filter tags

![Search and state of facet filters](https://user-images.githubusercontent.com/12818623/94175580-d9a6e680-fe64-11ea-9325-c30a1fdf391e.png)

2020-09-25 15:12 UTC, emyarod reviewed
hi @heatherco is there a GitHub issue attached to this PR? just looking for some more context around this change

2020-09-25 15:12 UTC, emyarod commented on src/data/index/watson-health/facet-filter-tags
> +date_added: YYY-MM-DDT00:00:00.000Z
I believe these fields need to be filled out to pass CI

2020-09-28 15:05 UTC, andreancardona requested changes
@heatherco following up with @emyarod 's comment :)

2020-09-30 17:57 UTC, tw15egan commented
Hey @heatherco, looks like there hasn't been any action taken on these PRs, so we're going to close them out for now. If you'd like these items to be added to the index, please fill out the `.yml` file and we can reopen the PR. Thanks!

2020-09-30 17:57 UTC, closed without merging