chore(release): update to v10.21.0
carbon-design-system/carbon-website pull request #1870
Opened 2020-10-06 17:43 UTC by tw15egan

Updates the website to the latest release

2020-10-06 20:00 UTC, emyarod approved these changes

2020-10-07 18:57 UTC, andreancardona commented
@tw15egan looks like there is a conflict with the `yarn.lock` file

2020-10-07 18:57 UTC, andreancardona requested changes
@tw15egan looks like there is a conflict with the `yarn.lock` file

2020-10-07 19:08 UTC, tw15egan commented
@andreancardona fixed! 👍

2020-10-09 16:24 UTC, joshblack approved these changes

2020-10-09 16:56 UTC, andreancardona approved these changes

2020-10-09 17:23 UTC, merged