fix(designing-tutorials): inline frame title
carbon-design-system/carbon-website pull request #1958
Opened 2020-11-05 19:20 UTC by andreancardona

Closes #1957 

Adds `titles` to newly added videos on `Designing -- Tutorials` page

Testing:

- [ ] Run Accessibility Checker & make sure the following error no longer shows up
<img width="1680" alt="Screen Shot 2020-11-05 at 3 15 43 PM" src="https://user-images.githubusercontent.com/32720851/98286385-50fa8a80-1f7a-11eb-90a3-a2f29c784183.png">

2020-11-05 19:55 UTC, tw15egan approved these changes
LGTM 👍 ✅

2020-11-06 13:32 UTC, emyarod approved these changes
should the titles be capitalized as titles as well in case it appears in a text pane? otherwise looks good to me

2020-11-09 12:28 UTC, andreancardona commented
> should the titles be capitalized as titles as well in case it appears in a text pane? otherwise looks good to me

Ooo good question - I'll defer to @jillianhowarth on that one

2020-11-09 14:52 UTC, jillianhowarth requested changes
@andreancardona @emyarod Yep! The titles should all use sentence case capitalization

2020-11-09 14:52 UTC, jillianhowarth commented on src/pages/designing/tutorials.mdx
> +<Video title="introduction to carbon" vimeoId="457802924" />
```suggestion
<Video title="Introduction to Carbon" vimeoId="457802924" />
```

2020-11-09 14:52 UTC, jillianhowarth commented on src/pages/designing/tutorials.mdx
> +<Video title="designing with carbon" vimeoId="457803206" />
```suggestion
<Video title="Designing with Carbon" vimeoId="457803206" />
```

2020-11-09 14:52 UTC, jillianhowarth commented on src/pages/designing/tutorials.mdx
> +<Video title="using 2x grid" vimeoId="457802917" />
```suggestion
<Video title="Using the 2x grid" vimeoId="457802917" />
```

2020-11-09 17:59 UTC, jillianhowarth approved these changes

2020-11-09 20:57 UTC, merged