update example with selectorPrimaryFocus
carbon-design-system/carbon-website pull request #2012
Opened 2020-11-25 14:41 UTC by balzss

#### Changelog

**Changed**

- updated example with `selectorPrimaryFocus`

**Removed**

- removed `primaryFocus` from example

2020-12-01 16:00 UTC, joshblack requested changes
Just some quick style nits 👀  thanks for doing this!

2020-12-01 16:00 UTC, joshblack commented on src/pages/components/overflow-menu/code.mdx
> +      selectorPrimaryFocus={'.optionTwo'}
```suggestion
      selectorPrimaryFocus="option-two"
```

2020-12-01 16:00 UTC, joshblack commented on src/pages/components/overflow-menu/code.mdx
> +        className="optionTwo"
```suggestion
        className="option-two"
```

2020-12-07 21:24 UTC, joshblack approved these changes

2020-12-08 16:21 UTC, tw15egan approved these changes

2020-12-09 23:29 UTC, merged