docs(button): addded danger variants
carbon-design-system/carbon-website pull request #2026
Opened 2020-12-02 19:27 UTC by aagonzales

Closes https://github.com/carbon-design-system/carbon-website/issues/1926
Closes https://github.com/carbon-design-system/carbon-website/issues/1983
Closes https://github.com/carbon-design-system/carbon-website/issues/1927

Danger button variants added to the website button usage and style tabs.

2020-12-02 20:13 UTC, janchild reviewed
@aagonzales looks great! Just some very minor copyedits.

2020-12-02 20:13 UTC, janchild commented on src/pages/components/button/usage.mdx
> +considering a required or primary step in a workflow should use the primary
```suggestion
considered a required or primary step in a workflow should use the primary
```

2020-12-02 20:13 UTC, janchild commented on src/pages/components/button/usage.mdx
> +<Caption>Examples of the primary, tertiary and ghost danger buttons</Caption>
```suggestion
<Caption>Examples of the primary, tertiary, and ghost danger buttons</Caption>
```

2020-12-02 20:13 UTC, janchild commented on src/pages/components/button/usage.mdx
> +| _Danger_    | For actions that could have destructive effects on the user’s data  (delete, remove, etc.). Danger button has three styles: primary, tertiary, and ghost.     |
```suggestion
| _Danger_    | For actions that could have destructive effects on the user’s data  (for example, delete or remove). Danger button has three styles: primary, tertiary, and ghost.     |
```

2020-12-02 20:19 UTC, laurenmrice requested changes
**Usage tab**

Modifiers image
-Ghost button tile: There should be `8px` space between `Ghost` and the `trash icon`.

2020-12-02 20:46 UTC, aagonzales commented
Ok fixed the ghost button images. Good catch!

2020-12-02 22:21 UTC, laurenmrice approved these changes
Awesome ! 🎉

2020-12-02 23:38 UTC, dakahn approved these changes

2020-12-03 13:38 UTC, janchild approved these changes
Hi @aagonzales, this is great! I'm approving. There are two small tweaks that I missed the first go around, if you could pls pop those in. Thank you!

2020-12-03 13:38 UTC, janchild commented on src/pages/components/button/usage.mdx
> +The danger button has three different styles: primary, tertiary and ghost.
```suggestion
The danger button has three different styles: primary, tertiary, and ghost.
```

2020-12-03 13:38 UTC, janchild commented on src/pages/components/button/usage.mdx
> +actions a user could choose then a lower emphasis style like the tertiary danger
```suggestion
actions a user could choose from, then a lower emphasis style like the tertiary danger
```

2020-12-03 16:35 UTC, tw15egan approved these changes

2020-12-03 17:22 UTC, merged