docs(inline loading): audit fixes
carbon-design-system/carbon-website pull request #2073
Opened 2021-01-08 20:00 UTC by aagonzales

Closes https://github.com/carbon-design-system/carbon-website/issues/2059

- Loading text to be `text-02`
- loading stroke be `interactive-04`
- Added finished and error states to color section
-  inline-loading__text should be 12px, label-01
- Updates states image (color section)
 - Update images

2021-01-08 20:00 UTC, joshblack approved these changes

2021-01-08 20:02 UTC, janchild approved these changes

2021-01-08 21:54 UTC, laurenmrice requested changes
<img width="839" alt="Screen Shot 2021-01-08 at 3 54 47 PM" src="https://user-images.githubusercontent.com/43969356/104068037-d8a68480-51c9-11eb-96a0-6145ef980be5.png">
-This old states image is still appearing:


-The Placement image/gif is not loading for me still. 
<img width="572" alt="Screen Shot 2021-01-08 at 3 51 06 PM" src="https://user-images.githubusercontent.com/43969356/104067882-967d4300-51c9-11eb-8bbf-31e94706a784.png">

2021-01-11 18:09 UTC, aagonzales commented
Oh weird some of my changes didn't show up in the preview link. It should be correct now. @laurenmrice

2021-01-11 19:06 UTC, laurenmrice approved these changes
🎉

2021-01-11 19:38 UTC, merged