docs(date picker): audit fixes
carbon-design-system/carbon-website pull request #2076
Opened 2021-01-13 18:54 UTC by aagonzales

Closes https://github.com/carbon-design-system/carbon-website/issues/2005

2021-01-13 21:05 UTC, janchild reviewed
@aagonzales this looks great! It might be good to add captions to the first two imaes on the Style tab, just for consistency.

2021-01-13 21:32 UTC, joshblack approved these changes

2021-01-13 22:22 UTC, laurenmrice requested changes
These images on the usage tab also need to use text-05 for placeholder text. (might be a problem with your build not updating? but just check them.)

- [ ] Anatomy: time picker
![time-picker-anatomy](https://user-images.githubusercontent.com/43969356/104517021-f6555e80-55ba-11eb-89f5-587f3736e51e.png)

- [ ] States: validation 
![date-picker-validation](https://user-images.githubusercontent.com/43969356/104517048-010ff380-55bb-11eb-9c58-b9407c15a53b.png)

- [ ] States: states image (validation input)
<img width="688" alt="Screen Shot 2021-01-13 at 3 49 10 PM" src="https://user-images.githubusercontent.com/43969356/104517072-0705d480-55bb-11eb-83c5-8095354b0394.png">

- [ ] Variants: date range picker anatomy
<img width="690" alt="Screen Shot 2021-01-13 at 3 49 35 PM" src="https://user-images.githubusercontent.com/43969356/104517155-24d33980-55bb-11eb-98be-5a24cbdb8028.png">


- [ ] Calendar behaviors: Min max dates
<img width="686" alt="Screen Shot 2021-01-13 at 3 49 44 PM" src="https://user-images.githubusercontent.com/43969356/104517168-2997ed80-55bb-11eb-8db6-1b90887ce3f9.png">


--------

- [ ] The helper text in the first input should be below the input.
<img width="757" alt="Screen Shot 2021-01-13 at 3 47 53 PM" src="https://user-images.githubusercontent.com/43969356/104517201-374d7300-55bb-11eb-9e05-f9d2545be12b.png">

2021-01-14 16:33 UTC, aagonzales commented
Ok fixed! I just forgot to update those on the usage page.

2021-01-14 16:47 UTC, janchild approved these changes
Thanks, @aagonzales!

2021-01-14 16:47 UTC, janchild commented on src/pages/components/date-picker/style.mdx
> +  Examplea of a single date calendar picker (left) and a date range calendar
```suggestion
  Example of a single date calendar picker (left) and a date range calendar
```

2021-01-14 16:47 UTC, janchild commented on src/pages/components/date-picker/style.mdx
> +<Caption>Example of date picker input states.</Caption>
```suggestion
<Caption>Examples of date picker input states</Caption>
```

2021-01-14 18:26 UTC, laurenmrice approved these changes
🙌🏻 🎉

2021-01-14 20:34 UTC, merged