docs(dropdown): audit style
carbon-design-system/carbon-website pull request #2103
Opened 2021-01-26 14:56 UTC by aagonzales

Closes https://github.com/carbon-design-system/carbon-website/issues/1997

2021-01-26 15:19 UTC, alisonjoseph commented on src/pages/components/dropdown/style.mdx
> +<Caption>Dropdown sizes | px / rem<</Caption>
```suggestion
<Caption>Dropdown sizes | px / rem</Caption>
```

2021-01-26 18:53 UTC, laurenmrice requested changes
Looks awesome!!! I like the friendly name formats in the tables. Just a couple small image tweaks for consistency:

-------


**Multi-select states:**
- Missing alert icon for error state
- First menu option in the selected state dropdown should say "Option 1" to be consistent with the other menus.
<img width="1061" alt="multi-select" src="https://user-images.githubusercontent.com/43969356/105889674-1120cd80-5fd4-11eb-935a-83d0f098cba1.png">

-------

**Inline states:**
- "Label" in the open focus state should read  "Choose an option"
<img width="1048" alt="inline" src="https://user-images.githubusercontent.com/43969356/105889993-678e0c00-5fd4-11eb-91ab-6adca7c88f20.png">

-------

Sizes:
- The prompt text should have the "..." after the text to be consistent with prompt text in other images.
<img width="897" alt="sizes" src="https://user-images.githubusercontent.com/43969356/105890008-6c52c000-5fd4-11eb-8716-f813ba0db48f.png">

-------

**Multi-select spec:**
- The 8px padding bottom indicator in the open state is off center with the padding opacity rectangle.
- The drop shadow does not go all the way to the bottom of the menu
<img width="842" alt="multi-select spec" src="https://user-images.githubusercontent.com/43969356/105890636-3c57ec80-5fd5-11eb-935e-edf223ad7a69.png">

2021-01-26 20:04 UTC, aagonzales commented
omg thank you for always looking at the images so closely @laurenmrice! good catches! They should be fixed now.

2021-01-26 20:41 UTC, laurenmrice approved these changes
Looks good to me ! 🎉

2021-01-27 15:32 UTC, janchild reviewed
@aagonzales just a few little content tweaks here. :) 
Multi words don't have a hyphen; they're joined into one word. And combo box is two words.

2021-01-27 15:32 UTC, janchild commented on src/pages/components/dropdown/style.mdx
> +  Dropdown variant examples: default, inline, multi-select, combo-box.
```suggestion
  Dropdown variant examples: default, inline, multiselect, combo box.
```

2021-01-27 15:32 UTC, janchild commented on src/pages/components/dropdown/style.mdx
> +<Caption>Dropdown and combo-box states</Caption>
```suggestion
<Caption>Dropdown and combo box states</Caption>
```

2021-01-27 15:32 UTC, janchild commented on src/pages/components/dropdown/style.mdx
> +<Caption>Multi-select dropdown states</Caption>
```suggestion
<Caption>Multiselect dropdown states</Caption>
```

2021-01-27 15:32 UTC, janchild commented on src/pages/components/dropdown/style.mdx
> +<Caption>Inline dropdown states.</Caption>
```suggestion
<Caption>Inline dropdown states</Caption>
```

2021-01-27 15:32 UTC, janchild commented on src/pages/components/dropdown/style.mdx
> +![Spacing for combo-box dropdown](images/dropdown-style-6.png)
```suggestion
![Spacing for combo box dropdown](images/dropdown-style-6.png)
```

2021-01-27 15:32 UTC, janchild commented on src/pages/components/dropdown/style.mdx
> +<Caption>Spacing for combbo-box dropdown | px / rem</Caption>
```suggestion
<Caption>Spacing for combo box dropdown | px / rem</Caption>
```

2021-01-27 15:48 UTC, janchild approved these changes
🎉

2021-01-28 00:39 UTC, dakahn approved these changes

2021-01-28 18:46 UTC, aledavila approved these changes

2021-01-28 19:58 UTC, merged