[docs] update button link for weekly playbacks
carbon-design-system/carbon-website pull request #2159
Opened 2021-03-02 17:09 UTC by laurenmrice

**Changed**

Meetups page:
- Updated the tertiary button to say `Enroll` for the Weekly Playbacks section.
- Linked the tertiary button to our YL event page for people to directly enroll to get meeting invites.

2021-03-02 17:11 UTC, joshblack approved these changes

2021-03-02 18:14 UTC, dakahn approved these changes

2021-03-03 16:07 UTC, janchild requested changes
Holding this for now while we do a full review of the content in all places. Should be done by Tueday March 9. Thank you.

2021-03-15 18:11 UTC, janchild reviewed
@laurenmrice I just updated this to the new link. Would you mind doing a double-check? Thank you!

2021-03-15 18:11 UTC, janchild commented on src/pages/whats-happening/meetups/index.mdx
> +  href="https://ec.yourlearning.ibm.com/w3/meeting/10154096">
```suggestion
  href="https://ec.yourlearning.ibm.com/w3/series/10163237">
```

2021-03-15 18:56 UTC, janchild approved these changes
💪  🏆  🍹

2021-03-15 19:42 UTC, merged