docs(number-input): v11 color token updates
carbon-design-system/carbon-website pull request #2317
Opened 2021-05-18 18:52 UTC by johnbister

This PR updates the color tokens on the style tab for the number-input component.

2021-05-18 19:20 UTC, aagonzales requested changes

2021-05-18 19:20 UTC, aagonzales commented on src/pages/components/number-input/style.mdx
> +| `.bx--number:disabled`                      | background-color | `$layer-disabled`         |
This would actually be `$field-disabled` since it uses the `$field` token on enabled.

2021-05-18 19:20 UTC, aagonzales commented on src/pages/components/number-input/style.mdx
> +| `.bx--number input[type='number']:disabled` | text color       | `$text-on-color-disabled` |
I think was a wrong token before should have been `$disabled-02` here so now its just `$text-disabled`

2021-05-19 15:54 UTC, aagonzales approved these changes
Perfect!

2021-05-19 22:09 UTC, dakahn approved these changes

2021-05-20 14:31 UTC, joshblack approved these changes

2021-05-20 17:45 UTC, merged