docs: v11 color token updates for overflow menu component
carbon-design-system/carbon-website pull request #2320
Opened 2021-05-18 19:51 UTC by johnbister

This PR updates the color tokens on the style tab for the overflow menu component.

2021-05-18 19:53 UTC, joshblack approved these changes

2021-05-18 20:50 UTC, aagonzales requested changes

2021-05-18 20:50 UTC, aagonzales commented on src/pages/components/overflow-menu/style.mdx
> +| `option:hover`             | background-color | `$background-hover`    |
This would be `$layer-hover`

2021-05-18 20:50 UTC, aagonzales commented on src/pages/components/overflow-menu/style.mdx
> +| `.bx--overflow-menu-options__option--danger` | background-color | `$support-error`                 |
This is an bug doc reference, should have been `ui-01` as well here. So change to `$layer`

2021-05-18 21:44 UTC, tw15egan approved these changes
LGTM once Anna's changes are made 👍🏻

2021-05-19 15:32 UTC, aagonzales approved these changes

2021-05-20 14:26 UTC, jillianhowarth approved these changes

2021-05-20 17:18 UTC, merged