Audit avt1 component demo label text area
carbon-design-system/carbon-website pull request #2335
Opened 2021-05-20 20:46 UTC by andreancardona

Closes #1596 

#### Changelog

- adds a label around the LiveEditor component demo to be screen reader accessible

#### Testing

- [ ] Checkout the Code snippet --> usage page
- [ ] Make sure you no longer see the `text area` missing label error documented in the issue above

2021-05-24 18:14 UTC, tw15egan requested changes
Had a few comments

2021-05-24 18:14 UTC, tw15egan commented on src/components/ComponentDemo/ComponentDemo.js
> +                </label>
```suggestion
                <label htmlFor="live-editor-label">
                    <span className="live-editor-label">{labelText}</span>
                  </label>
                  <LiveEditor
                    padding={16}
                    style={{ overflowX: 'auto', whiteSpace: 'pre' }}
                    onChange={(updatedCode) => setCode(updatedCode)}
                    className={editorContainer}
                    textareaId="live-editor-label"
                  />
```

I'm still seeing a violation with this format. I don't think we need to wrap the entire `LiveEditor` in the `label`.

The label text was also being parsed strangely rendering it here for some reason. I moved it to before the render method and added something like

```jsx
const labelText = `Live editor for the ${components[0].label} component`;
```

2021-05-31 17:15 UTC, jnm2377 approved these changes

2021-06-01 17:27 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-06-01 17:55 UTC, merged