v11 color token updates for select component
carbon-design-system/carbon-website pull request #2341
Opened 2021-05-21 15:13 UTC by kingtraceyj

This PR updates the color tokens on the Style tab for the select component.

2021-05-21 15:55 UTC, aagonzales requested changes

2021-05-21 15:55 UTC, aagonzales commented on src/pages/components/select/style.mdx
> +| `.bx--select-input`   | background | `$background`               |
The would be `$field`

2021-05-21 15:55 UTC, aagonzales commented on src/pages/components/select/style.mdx
> +| `.bx--select--light`  | background | `$background: inline theme` |
And you can delete this row. We're not showing the `light` variants anymore. You'd only us "inline theme" if the components require that version for the default style, like within Modal.

2021-05-21 15:55 UTC, aagonzales commented on src/pages/components/select/style.mdx
> +| `.bx--select-input:disabled`      | background | `$background-disabled` |
This would be `$field-disabled`

2021-05-24 19:41 UTC, aagonzales approved these changes

2021-05-24 23:00 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-05-24 23:56 UTC, merged