docs(popover): new component usage and style tab content
carbon-design-system/carbon-website pull request #2459
Opened 2021-07-23 20:01 UTC by laurenmrice

**New**

Usage tab:
- Usage documentation
- Usage images

Style tab:
- Style documentation
- Style images

---

**Testing**
- Go to `Components` --> `Popover`
  - Review Usage tab
  - Review Style tab

2021-07-27 15:48 UTC, theiliad requested changes

2021-07-27 15:48 UTC, theiliad commented on src/pages/components/popover/style.mdx
> +A popover is a layer that pops up over all other elements on a page.
```suggestion
description: A popover is a layer that pops up over all other elements on a page.
```

2021-08-24 00:08 UTC, jeanservaas approved these changes
Looks great!

2021-08-31 13:33 UTC, laurenmrice commented
Ready for one more review from dev when you get a chance @joshblack or @dakahn  👀

2021-09-01 21:18 UTC, dakahn approved these changes

2021-09-02 13:58 UTC, theiliad approved these changes
LGTM

2021-09-02 13:58 UTC, merged