chore: update theme and other dependencies
carbon-design-system/carbon-website pull request #2602
Opened 2021-10-28 17:57 UTC by vpicone

2021-11-03 20:03 UTC, dakahn approved these changes

2021-11-04 12:57 UTC, alisonjoseph requested changes
![Screen Shot 2021-11-04 at 7 56 49 AM](https://user-images.githubusercontent.com/2753488/140317292-364eb526-defb-4977-b2f4-c338bdca3605.png)

Still not seeing the latest updates to the medium post component styles for some reason 🤔

2021-11-04 13:27 UTC, alisonjoseph commented
@vpicone I think I figured it out. We need to remove this since its in the theme https://github.com/carbon-design-system/carbon-website/tree/main/src/gatsby-theme-carbon/components/MediumPosts

2021-11-04 13:45 UTC, alisonjoseph approved these changes
will open a new PR to remove shadowed MediumPost component

2021-11-04 13:45 UTC, merged