fix: medium card color on news and articles page
carbon-design-system/carbon-website pull request #2620
Opened 2021-11-05 17:35 UTC by alisonjoseph

Should be showing up light not dark.

2021-11-05 17:40 UTC, jnm2377 approved these changes

2021-11-05 19:25 UTC, tay1orjones approved these changes

2021-11-08 16:41 UTC, laurenmrice reviewed
- The preview link is still showing the dark cards.

- Also this may be unrelated to changing just the color of the articles in this PR, but Ariella Gilmores card if not the same height as the others. 
<img width="1037" alt="Screen Shot 2021-11-08 at 10 39 27 AM" src="https://user-images.githubusercontent.com/43969356/140782202-ff36f61d-2449-4fb7-96f8-b005f9c3975d.png">

2021-11-08 16:42 UTC, alisonjoseph commented
I think there must be an upstream bug with this component, unless I'm missing something @vpicone @sstrubberg  🤔

2021-11-08 16:45 UTC, vpicone requested changes

2021-11-08 16:45 UTC, vpicone commented on src/pages/whats-happening/news-and-articles/index.mdx
> +<MediumPosts postLimit={9} color="light" />
```suggestion
<MediumPosts postLimit={9} cardProps={{color: "light"}} />
```

2021-11-08 18:24 UTC, laurenmrice approved these changes
The cards are showing up as "light" now. That one card is still off size wise but it seems like a different problem to be addressed in another PR.

2021-11-08 18:47 UTC, vpicone approved these changes

2021-11-08 18:48 UTC, merged