Toggletip style v11
carbon-design-system/carbon-website pull request #2652
Opened 2021-11-29 16:18 UTC by kingtraceyj

Added Toggletip style page to v11 

### New
- updated tokens
- added new images

2021-12-17 17:14 UTC, aagonzales requested changes
Overall looks good, just a few small things.

2021-12-17 17:14 UTC, aagonzales commented on src/pages/components/toggletip/style.mdx
> +**Interactive states**
```suggestion
 <br />
#### Interactive states
```

2021-12-17 17:14 UTC, aagonzales commented on src/pages/components/toggletip/style.mdx
> +**Interactive states**
We normally add a line break for extra spacing when adding an H4 above a table.

2021-12-17 17:14 UTC, aagonzales commented on src/pages/components/toggletip/style.mdx
> +| Body text | 14px / 0.875rem    | Regular / 400 | `$body-long-01` |
```suggestion
| Body text | 14px / 0.875rem    | Regular / 400 | `$body-01` |
```

Using the new [v11 type styles](https://v11.carbondesignsystem.com/guidelines/typography/type-sets#body-styles).

2021-12-17 17:14 UTC, aagonzales commented on src/pages/components/toggletip/style.mdx
> +| Element   | font-size (px-rem) | font-weight   | type token      |
```suggestion
| Element   | Font-size (px-rem) | Font-weight   | Type token      |
```

2021-12-17 17:14 UTC, aagonzales commented on src/pages/components/toggletip/style.mdx
> +![Placement examples for a toggletip](images/toggletip-style-3.png)
In this last image the top line of the spec if misaligned 
![image](https://user-images.githubusercontent.com/11670886/146582398-e6e12280-532e-487e-b712-d930c550d8ad.png)

2022-01-04 15:54 UTC, aagonzales approved these changes

2022-01-04 16:48 UTC, laurenmrice approved these changes
Looks great! 🎉

2022-01-04 17:18 UTC, abbeyhrt approved these changes

2022-01-12 21:03 UTC, merged