Add definition tooltip
carbon-design-system/carbon-website pull request #2671
Opened 2021-12-16 15:50 UTC by kingtraceyj

#### Changelog

**New**

• Added definition tooltip docs into tooltip from toggletip

**Changed**

• Updated images
• Updated style tables and images

2022-01-04 02:16 UTC, dakahn approved these changes

2022-01-04 16:53 UTC, laurenmrice approved these changes
✅

2022-01-18 20:38 UTC, laurenmrice requested changes
The image for Definition tooltip should be updated to cahnge the label in the images from toggletip to `tooltip`.
<img width="694" alt="Screen Shot 2022-01-18 at 2 37 42 PM" src="https://user-images.githubusercontent.com/43969356/150014730-e05da01a-ffc7-44f3-888b-fef00d592af9.png">

2022-01-18 20:38 UTC, laurenmrice commented on src/pages/components/tooltip/style.mdx
> +| element   | property         | color token           |
The column header names should be capitalized.

2022-01-18 20:38 UTC, laurenmrice commented on src/pages/components/tooltip/style.mdx
> +### Definition toggletip
This is technically a tooltip now right? Not toggletip?

2022-01-18 20:38 UTC, laurenmrice commented on src/pages/components/tooltip/style.mdx
> +#### Interactive states
The "Interactive states" heading seems to have the incorrect padding between the heading and the table below it.

2022-01-26 16:05 UTC, kingtraceyj commented
@laurenmrice i added breaks after the interactive state headings ... let me know if that's what it's supposed to look like! it's better than before but now it seems like such a large break.

2022-01-26 17:07 UTC, laurenmrice approved these changes

2022-01-26 17:45 UTC, merged