Accessibility changes
carbon-design-system/carbon-website pull request #2737
Opened 2022-02-15 23:09 UTC by mbgower

Added 5 images and all new content to the Accessibility tab for code snippet.
Removed the Screen Reader testing material from the Usage page, and made one minor editorial that seemed acceptable during the playback.

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2022-02-16 01:48 UTC, mjabbink commented
@mbgower Thanks for tackling this! This is great. The next steps are for the design team to provide some feedback or do the design detailing on them illustrations and they need to span 8-columns in the page layout. Can you connect with @aagonzales to see who can support you on these improvements. Much thanks.

2022-02-16 06:14 UTC, mbgower commented
thanks @mjabbink 
Yeah, I wasn't sure if it was supposed to be 8. I'll adjust.
FYI, up until now we've been having these rewrites reviewed by CAG during handoffs.
@laurenmrice has looked over the ones we've done to date.

I thought I'd try this way to see if we could accelerate the changes. Here's what I'm doing this time:
- [x] propose to get access to do our own PR
- [ ] create a branch with our suggested changes
- [ ] walk through the PR as part of hand off
- [ ] if possible, implement the accessibility page as part of PR?
- [ ] potentially opportunity for knowledge share on rudiments of github/PR to a11y designers

2022-02-16 16:14 UTC, tay1orjones requested changes

2022-02-16 16:14 UTC, tay1orjones commented on src/pages/components/code-snippet/accessibility.mdx
> +– single line snippets take an additional tabstop to support arrow key scrolling
I think these need an empty line above them and a simple dash to get the proper list styling. Right now it looks like this 
![image](https://user-images.githubusercontent.com/3360588/154307887-cab98e94-eb5c-4e35-9645-ac1cd4018e1f.png)


```suggestion
Keep this in mind if you’re modifying Carbon or creating a custom component:

- The inline code text is implemented as a button so its text can be copied
- Single line snippets take an additional tabstop to support arrow key scrolling
```

2022-02-25 21:01 UTC, joshblack approved these changes

2022-02-25 22:30 UTC, tay1orjones approved these changes

2022-02-28 20:49 UTC, tay1orjones commented
recheck

2022-03-02 18:08 UTC, laurenmrice reviewed
@mbgower 
- I see the revised images! ✅
- Question: For any time we reference a keyboard function like `Space`, `Enter`, `Tab`, etc should we style them as code in markdown like we do on the Usage tab for the [Interactions section](https://carbondesignsystem-5mdpu7tkp-carbon-design-system.vercel.app/components/code-snippet/usage/#interactions) for consistency? We typically do this for all components.
- Also I understand that the word "Labelling" is technically correct and is the preferred spelling in the UK, while "Labeling" is the preferred spelling in the US. Not sure if it matters from a content perspective but wanted to note it here.

2022-03-02 18:28 UTC, mbgower commented
I will update the keys to make them like code.
It's funny you mentioned "labelling". I noticed that yesterday.
the specification uses aria-labelledby, etc.
I'll double check IBM Style and update non-technical uses accordingly.

2022-03-02 19:30 UTC, laurenmrice approved these changes
Looks good to me 🎉

2022-03-02 19:59 UTC, merged

2022-03-02 23:32 UTC, mjabbink commented
Seeing this now brings up wether mixing the two type of beginning and endings together. I did not think of that yesterday. I have a solution below that would allow (at least in this case) to maintain that little vertical straight segment and the beginning/ending of the large arch.

It requires some shifting to the right on the code snip and reducing the largest arch down.

<img width="932" alt="Screen Shot 2022-03-02 at 5 25 23 PM" src="https://user-images.githubusercontent.com/32881239/156467284-0a8ef9b6-39d5-4702-a988-66905406ef97.png">

2022-03-02 23:34 UTC, laurenmrice commented
@mjabbink Thanks Mike, I will change this in the next iteration of Code snippet. 👍

2022-03-02 23:42 UTC, mjabbink commented
or you can divide the code field into 4 units and use that to place the arch?
<img width="1012" alt="Screen Shot 2022-03-02 at 5 41 37 PM" src="https://user-images.githubusercontent.com/32881239/156468380-3d0ec605-14f1-4091-a0bb-6351c4d341de.png">

2022-03-02 23:43 UTC, mjabbink commented
or just use a small one and start the next tab from the center of the code field?

<img width="901" alt="Screen Shot 2022-03-02 at 5 35 13 PM" src="https://user-images.githubusercontent.com/32881239/156468450-5e882eae-3628-49e6-96fc-59fb22be00e3.png">

2022-03-02 23:44 UTC, mjabbink commented
Not sure if the little straight segment is going to be a major pain all the time or only on occasion. Otherwise maybe the purple half circle might be better (as long as arrows are vertical or horizontal).

2022-03-03 00:09 UTC, mbgower commented
@mjabbink All great things to chew on. With a long horizontal target, there is more flexibility here than on some other components. As Lauren says, if we keep that in mind for other components we're updating images for, we can go back and choose which one seems to work better for other components

2022-03-03 20:36 UTC, mjabbink commented
@mbgower I recommend adding the “why” or “benefit”. I feel like if we say statement like this then we should follow up with why we do it or the benefit to the users.

Current
**What Carbon provides**
Carbon bakes keyboard operation into its components, as well as many other accessibility considerations. Could be an opportunity to educate.


Suggestion
**What Carbon provides**
Carbon bakes keyboard operation into its components, as well as many other accessibility considerations. This allows for... benefits, advantages... the why.