v11(docs): spacing page updates
carbon-design-system/carbon-website pull request #2793
Opened 2022-03-17 19:08 UTC by aagonzales

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2022-03-17 21:08 UTC, aagonzales commented
@tay1orjones Is this enough for `stack` on the overview page?

2022-03-17 21:42 UTC, tay1orjones requested changes
@aagonzales Yes, fantastic! One small change needed to the image path to make sure it'll render though.

2022-03-17 21:42 UTC, tay1orjones commented on src/pages/guidelines/spacing/overview.mdx
> +![Example of spacing tokens applied with the stack component](images/spacing-stack.png.png)
```suggestion
![Example of spacing tokens applied with the stack component](images/spacing-stack.png)
```

2022-03-17 21:55 UTC, tay1orjones approved these changes

2022-03-18 18:44 UTC, joshblack approved these changes

2022-03-18 18:53 UTC, laurenmrice approved these changes
Looks great! 🚀

2022-03-18 19:48 UTC, merged