2848 update typography page
carbon-design-system/carbon-website pull request #2855
Opened 2022-04-04 18:24 UTC by dakahn

Closes #2848 

Updates various imports and usage docs for v11.

2022-04-04 20:34 UTC, aagonzales approved these changes

2022-04-05 15:12 UTC, joshblack requested changes

2022-04-05 15:12 UTC, joshblack commented on src/pages/guidelines/typography/code.mdx
> -@import '@carbon/type/scss/classes';
Could you add a code snippet that details how to bring in the classes into a product's CSS?

2022-04-05 15:48 UTC, jnm2377 approved these changes
looks good after the changes Josh requested

2022-04-11 16:01 UTC, merged