fix: convert inline styles to objects and fix mdx formatting
carbon-design-system/carbon-website pull request #2946
Opened 2022-05-19 14:18 UTC by alisonjoseph

Closes #

The Platform is using v2 of mdx which requires styles to be formatted as objects. 

#### Changelog

- Converted all inline styles to objects
- Fixed formatting in code mdx files to prevent [`Unexpected end of file in expression, expected a corresponding closing brace for {” error?`
](https://mdxjs.com/docs/troubleshooting-mdx/#unexpected-end-of-file-in-expression-expected-a-corresponding-closing-brace-for-)

2022-05-19 20:06 UTC, joshblack requested changes
Looking great! Just noticed some of the replacements seem to have `sstyle` instead of `style` and was curious if that was intentional. When looking at things like the UI Shell demo they seem to be acting odd so just wanted to bring it up.

2022-05-19 20:06 UTC, joshblack commented on src/pages/components/UI-shell-header/code.mdx
> +      sstyle={{
```suggestion
      style={{
```

2022-05-19 20:06 UTC, joshblack commented on src/pages/components/UI-shell-header/code.mdx
> +      sstyle={{
```suggestion
      style={{
```

2022-05-19 20:06 UTC, joshblack commented on src/pages/components/UI-shell-header/code.mdx
> +      sstyle={{
```suggestion
      style={{
```

2022-05-19 20:06 UTC, joshblack commented on src/pages/components/UI-shell-header/code.mdx
> +      sstyle={{
```suggestion
      style={{
```

2022-05-19 22:13 UTC, alisonjoseph commented
oops 🤦‍♀️ Fixed @joshblack

2022-05-20 18:21 UTC, joshblack approved these changes

2022-05-20 20:49 UTC, aledavila approved these changes

2022-05-24 14:53 UTC, merged