Link accessibility update
carbon-design-system/carbon-website pull request #3009
Opened 2022-06-23 17:01 UTC by mbgower

Added 3 images and new text content to accessibility tab

2022-06-27 16:44 UTC, tw15egan approved these changes
Just need to run `yarn format` to fix the failing tests, other changes look great 👍🏻

2022-06-27 17:20 UTC, dakahn approved these changes

2022-06-27 21:06 UTC, laurenmrice requested changes
Looks good! Just a couple content things to edit:

2022-06-27 21:06 UTC, laurenmrice commented on src/pages/components/link/accessibility.mdx
> +  for more details.
```suggestion
  for more details
```

2022-06-27 21:36 UTC, mbgower commented on src/pages/components/link/accessibility.mdx
> +  Links are reached by `Tab` key and activated by `Space` and `Enter` keys.
done

2022-06-28 14:10 UTC, laurenmrice approved these changes

2022-06-28 17:54 UTC, merged