messaging tweaks
carbon-design-system/carbon-website pull request #3014
Opened 2022-06-24 20:45 UTC by mbgower

minor changes to improve the image and dev info for the progress bar accessibility output

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2022-06-24 20:47 UTC, mbgower commented
@thyhmdo the image should have been purple to match the convention. Took the opportunity to better link the dev info and this image content

2022-06-27 17:39 UTC, dakahn approved these changes

2022-06-28 14:06 UTC, laurenmrice requested changes
For the first two images on the Progress bar accessibility page, let's use the revised images in this [box folder](https://ibm.ent.box.com/folder/166326368794) with some adjusted alignments.

2022-06-28 15:01 UTC, mbgower commented
@laurenmrice images updated

2022-06-28 17:39 UTC, laurenmrice approved these changes

2022-06-28 17:56 UTC, tw15egan approved these changes

2022-06-28 19:15 UTC, merged