docs(date-picker): gower review
carbon-design-system/carbon-website pull request #3096
Opened 2022-08-16 19:19 UTC by aagonzales

Related https://github.com/carbon-design-system/carbon-website/issues/3045

Recommended immediate updates from @mbgower's review of the date picker docs. Some updates in Mike's original PDF like page structure will be addressed in a future issue. 

[See issue](https://github.com/carbon-design-system/carbon-website/issues/3045#issuecomment-1204289674) for list of changes applied in this PR.

2022-08-17 02:48 UTC, dakahn approved these changes

2022-08-17 15:00 UTC, laurenmrice requested changes
- On the Style tab under the Structure section for "Time picker", the end of the description sentence has a typo of `Hi` that should be removed.
<img width="977" alt="Screen Shot 2022-08-17 at 10 50 27 AM" src="https://user-images.githubusercontent.com/43969356/185171509-acfb4cc9-b4e3-4ff5-8f19-8ddac65aa0c4.png">

- When you show the open calendar menu in images, the previous/next month days should be using `$text-secondary` color token. I think this is a bug in the symbol itself and it just needs to be updated. Might be better to update those images in a later PR once the bug is fixed in the symbol so we don't have to break them all?

<img width="434" alt="Screen Shot 2022-08-17 at 10 54 15 AM" src="https://user-images.githubusercontent.com/43969356/185172094-f11caa5c-a2e7-4d46-8914-211e79f4b9e4.png">

2022-08-17 15:00 UTC, laurenmrice commented on src/pages/components/date-picker/usage.mdx
> +- When asking the user for an exact, approximate, or memorable date or time
```suggestion
- When asking the user for an exact, approximate, or memorable date or time.
```

2022-08-17 15:00 UTC, laurenmrice commented on src/pages/components/date-picker/usage.mdx
> +- For scheduling tasks
```suggestion
- For scheduling tasks.
```

2022-08-17 15:54 UTC, aagonzales commented
Oh no, that's a problem with the library component. I'll have to push a change from there first to update the calendars. Good catch though

2022-08-18 13:27 UTC, tay1orjones approved these changes

2022-08-18 16:04 UTC, laurenmrice approved these changes
🎉

2022-08-18 17:44 UTC, merged