Update accessibility.mdx
carbon-design-system/carbon-website pull request #3143
Opened 2022-09-09 19:50 UTC by mbgower

Update to Accessibility content.
Still need to upload images

2022-09-16 18:53 UTC, tay1orjones approved these changes

2022-09-20 19:24 UTC, laurenmrice requested changes
@mbgower Looks good! Just a couple of typos and content comments.

2022-09-20 19:24 UTC, laurenmrice commented on src/pages/components/UI-shell-header/accessibility.mdx
> +Each element in the header can be reached by `Tab` key. A "Skip to main content" link appears when a
```suggestion
Each element in the header can be reached by the `Tab` key. A "Skip to main content" link appears when a
```

2022-09-20 19:24 UTC, laurenmrice commented on src/pages/components/UI-shell-header/accessibility.mdx
> +  Carbon applies a header region around the whole header UI shell.
```suggestion
  Carbon applies a header region around the whole UI shell header.
```

2022-09-20 19:24 UTC, laurenmrice commented on src/pages/components/UI-shell-header/accessibility.mdx
> +Carbon provides default names for each icon-only button in the header, and these names are revealed on hover or focus. Interactions for some header components are covered under other component topics
```suggestion
Carbon provides default names for each icon-only button in the header, and these names are revealed on hover or focus. Interactions for some header components are covered under other component topics such as [search](/components/search/usage), [notifications](/components/notifications/usage), and the [UI shell right panel switcher](components/UI-shell-right-panel/usage/#switcher).  
```

2022-09-20 19:24 UTC, laurenmrice commented on src/pages/components/UI-shell-header/accessibility.mdx
> +  Carbon provides default names for its icon-only components, and reveals them on hover or focus.
```suggestion
  Carbon provides default names for its icon-only components and reveals them on hover or focus.
```

2022-09-20 19:24 UTC, laurenmrice commented on src/pages/components/UI-shell-header/accessibility.mdx
> +<Caption>Annotate your header, even if your design matches the default Carbon UI shell header behavior.</Caption>
```suggestion
<Caption>Annotate the header, even if your design matches the default Carbon UI shell header behavior.</Caption>
```

2022-09-20 19:24 UTC, laurenmrice commented on src/pages/components/UI-shell-header/accessibility.mdx
> +<Caption>Annotate if your design modifes the default keyboard or component interaction.</Caption>
```suggestion
<Caption>Annotate if the design modifies the default keyboard or component interaction.</Caption>
```

2022-09-20 19:24 UTC, laurenmrice commented on src/pages/components/UI-shell-header/accessibility.mdx
> +- Carbon includes the Skip to main content link as the first item on the page with a `tabindex="0"`, but hides it through CSS until it receives focus.
```suggestion
- Carbon includes the "Skip to main content" link as the first item on the page with a `tabindex="0"`, but hides it through CSS until it receives focus.
```

2022-09-20 20:48 UTC, mbgower commented
@laurenmrice I accepted all those changes.

2022-09-20 21:12 UTC, laurenmrice approved these changes
Looks good to me!

2022-09-21 15:14 UTC, tay1orjones approved these changes

2022-09-21 15:47 UTC, merged