Change tab text of typography from "Styling strategies" to "Style strategies"
carbon-design-system/carbon-website pull request #3163
Opened 2022-09-19 17:27 UTC by abhilipsasahoo03

Closes #3148 

**Change log**

- Changed tab text of typography section by replacing "Styling strategies" with "Style strategies"

- Updated corresponding links to "Style strategies" in the pages

2022-09-19 17:31 UTC, abhilipsasahoo03 commented
I have read the DCO document and I hereby sign the DCO.

2022-09-20 11:36 UTC, abhilipsasahoo03 commented
@kingtraceyj @tay1orjones kindly look into this and let me know if any change is required.

2022-09-20 14:18 UTC, aagonzales approved these changes
This looks good but should we add a redirect incase other pages on the site were also linking to the old tab name page?

2022-09-20 18:44 UTC, tay1orjones requested changes
Good catch on the redirects - @abhilipsasahoo03 the redirect can be placed alongside these others https://github.com/carbon-design-system/carbon-website/blob/e0059b25c61478950b18258e4187465fd4771d79/gatsby-node.js#L64-L68

2022-09-20 19:08 UTC, abhilipsasahoo03 commented
> Good catch on the redirects - @abhilipsasahoo03 the redirect can be placed alongside these others https://github.com/carbon-design-system/carbon-website/blob/e0059b25c61478950b18258e4187465fd4771d79/gatsby-node.js#L64-L68

Hi @tay1orjones @aagonzales I have added the redirect...kindly review.

2022-09-20 19:23 UTC, tay1orjones commented on gatsby-node.js
> +   });
Sorry just some minor formatting here that I can suggest and commit

```suggestion
  createRedirect({
    fromPath: '/guidelines/typography/styling-strategies',
    toPath: '/guidelines/typography/style-strategies', 
    isPermanent: true,
  });
```

2022-09-20 19:23 UTC, tay1orjones approved these changes

2022-09-20 19:41 UTC, merged