Docs: Fluid dropdown
carbon-design-system/carbon-website pull request #3199
Opened 2022-10-12 22:37 UTC by aagonzales

Docs for fluid dropdown, combobox, multiselect

2022-10-14 16:08 UTC, tw15egan commented
@aagonzales I'm going to push up a PR that updates the `fluid-input` branch with the latest from `main` so this PR is cleaner

2022-10-17 21:06 UTC, laurenmrice requested changes
Looks great! Just a couple of things:

### Usage tab

**Multiselect > Second image**
- Something may be off in the second fixed/fluid image for Multiselect. The tag shifts from left to right between viewing fixed/fluid. I would double-check it to see if there is a spacing issue in one of them. 
![dropdown](https://user-images.githubusercontent.com/43969356/196279854-05660120-d0bf-45f1-9c79-1ecd68e87f0b.gif)

**Multiselect > Filtering section images**
First image: The “Data flows” option should be `$text-secondary`.
<img width="464" alt="Screen Shot 2022-10-17 at 4 31 38 PM" src="https://user-images.githubusercontent.com/43969356/196279904-8361ead2-0ff1-4019-810e-39be4c5d85b2.png">

Second image: I think the “Data visualizations” option should also be `$text-secondary` here since all search results have the same importance before hovering.
<img width="639" alt="Screen Shot 2022-10-17 at 4 32 46 PM" src="https://user-images.githubusercontent.com/43969356/196279920-1522a417-1d81-4ea2-ab27-02c71de7b783.png">

-------

### Style tab
**Interactions > Combobox fluid image:**
- The Warning state message should be `$text-primary`.

<img width="276" alt="Screen Shot 2022-10-17 at 4 49 17 PM" src="https://user-images.githubusercontent.com/43969356/196280805-a1a1c549-9928-4a4c-a90c-1d6923c9731b.png">

- The Item hover state is missing the cursor like you have shown in the fixed image.

**Sizes > Fluid image**
- The image size looks enlarged within the space. Also seems like the fixed image size is too small.

2022-10-17 21:12 UTC, laurenmrice requested changes

2022-10-17 21:12 UTC, laurenmrice commented on src/pages/components/dropdown/style.mdx
> +|              | margi-top, margin-bottom    | 13 / .8125 | –             |
```suggestion
|              | margin-top, margin-bottom    | 13 / .8125 | –             |
```

2022-10-17 21:12 UTC, laurenmrice commented on src/pages/components/dropdown/style.mdx
> +The field height and menu option height should always match. These sizes options
```suggestion
The field height and menu option height should always match. These size options
```

2022-10-17 21:12 UTC, laurenmrice commented on src/pages/components/dropdown/style.mdx
> +|           | Medium (sm) | 40 / 2.5        |
```suggestion
|           | Medium (md) | 40 / 2.5        |
```

2022-10-17 21:12 UTC, laurenmrice commented on src/pages/components/dropdown/usage.mdx
> +Carbpn rarely uses The dropdown menu has a style called `box-shadow` that is
```suggestion
The dropdown menu has a style called `box-shadow` that is
```

2022-10-18 15:10 UTC, laurenmrice approved these changes

2022-10-18 16:15 UTC, aagonzales commented
@tw15egan it's not showing any conflict anymore, can we just merge this one? Or should I still open a new clean one?

2022-10-18 17:13 UTC, tw15egan commented
As long as everything looks good on your end, I'm good with merging it 👍🏻

2022-10-18 17:17 UTC, tw15egan approved these changes

2022-10-18 17:57 UTC, merged