Fluid datepicker v2
carbon-design-system/carbon-website pull request #3243
Opened 2022-11-03 17:45 UTC by aagonzales

Closes https://github.com/carbon-design-system/carbon-website/issues/3190 
Closes https://github.com/carbon-design-system/carbon/issues/12476

Fluid DatePicker and Fluid TimePicker documentation update.

#### Changelog

- Updated Usage tab to include Fluid content
   - Added "Styling" section under Formatting
   - Added Fixed/Fluid tabs to certain images
- Updated Style tab to include Fluid content

2022-11-04 17:35 UTC, alisonjoseph commented
@aagonzales I can help with the merge conflicts, but I think I'll need permissions on your fork to do anything. 

https://github.com/aagonzales/carbon-website/  Settings > Collaborators > Add Collaborator

2022-11-04 17:41 UTC, aagonzales commented
@alisonjoseph ok I invited you

2022-11-04 18:43 UTC, alisonjoseph commented
@aagonzales should be resolved 🙏

2022-11-04 18:49 UTC, aagonzales commented
Thank you @alisonjoseph!!

2022-11-04 19:21 UTC, tw15egan approved these changes
LGTM 👍 ✅

2022-11-04 19:24 UTC, alisonjoseph approved these changes

2022-11-14 19:30 UTC, laurenmrice requested changes
Looks great! ⭐️ Just a couple of small things:

### Usage tab

**Styling section**
- In the image the label specifies (`mm/dd/yyy`). It is missing a fourth `y`. 
<img width="299" alt="Screen Shot 2022-11-14 at 2 28 25 PM" src="https://user-images.githubusercontent.com/43969356/201748395-6061b33b-d2dc-4d11-989e-12d52267e1c8.png">

- The cropped image of date picker menu needs border rules so it doesn’t blend in with the website background.
<img width="799" alt="Screen Shot 2022-11-14 at 2 28 47 PM" src="https://user-images.githubusercontent.com/43969356/201748471-ddb7f41a-58cf-4e32-a270-cc43abb83420.png">

**Alignment section**
- Image needs bottom border rules so it doesn’t blend in with the website background.
<img width="784" alt="Screen Shot 2022-11-14 at 2 29 18 PM" src="https://user-images.githubusercontent.com/43969356/201748557-89a5a384-ead7-4fae-b7b2-acf1a87f64b8.png">

**States section**
- Fluid image: The disabled state input has a different date than the other dates. There fixed disabled state image just has placeholder text. I would either do placeholder text or keep the same 05/19/2022 date for consistency. (This also appears in an image on the style tab)

2022-11-14 19:30 UTC, laurenmrice commented on src/pages/components/date-picker/usage.mdx
> +heights. The input is a set height of 64px expect when a warning or error
```suggestion
heights. The input is a set height of 64px except when a warning or error
```

2022-11-14 19:30 UTC, laurenmrice commented on src/pages/components/date-picker/usage.mdx
> +content should never horizontal scroll or overflow.
```suggestion
content should never horizontally scroll or overflow.
```

2022-11-16 20:12 UTC, aagonzales commented
Ok @laurenmrice I made those updates. I also went ahead and actually added TimePicker to this PR since it was still open if you want to check that content as well.

2022-11-17 19:35 UTC, laurenmrice requested changes
**Usage tab**
- [Time pickers section](https://carbondesignsystem-git-fork-aagonza-8a78b6-carbon-design-system.vercel.app/components/date-picker/usage#time-pickers): This was a current bug in the docs, but this sentence needs to have a word added to it

> The time field format should include the hour and minutes, for example 11:30. It may be localized `to` accommodate the 12-hour or 24-hour format.


**Style tab**
- This spec image for Time picker needs to have `$text-primary` warning text.
<img width="519" alt="Screen Shot 2022-11-17 at 2 28 21 PM" src="https://user-images.githubusercontent.com/43969356/202540514-62ab3dd5-5358-428f-85ef-d3579bb687a5.png">

- This spec image for Time picker need to have `$text-primary` for the "Timezone" dropdown text.
<img width="464" alt="Screen Shot 2022-11-17 at 2 31 53 PM" src="https://user-images.githubusercontent.com/43969356/202541566-48017d77-9b43-41da-b3aa-a2f7c9e0e12c.png">

2022-11-29 15:39 UTC, laurenmrice approved these changes
🎉

2022-11-29 15:44 UTC, merged