Update accessibility.mdx
carbon-design-system/carbon-website pull request #3251
Opened 2022-11-09 22:06 UTC by mbgower

Update to text content on Accessibility tab. Images not yet ready.

2022-11-28 19:58 UTC, tw15egan approved these changes

2022-11-29 15:46 UTC, laurenmrice requested changes

2022-11-29 15:46 UTC, laurenmrice commented on src/pages/components/tree-view/accessibility.mdx
> +branch is open, `Right arrow` moves into the first child node. Pressing the
```suggestion
branch is open, the `Right arrow` moves into the first child node. Pressing the
```

2022-11-29 15:46 UTC, laurenmrice commented on src/pages/components/tree-view/accessibility.mdx
> +`Space` or `Enter` keys
```suggestion
`Space` or `Enter` keys.
```

2022-11-30 15:27 UTC, laurenmrice approved these changes

2022-11-30 15:32 UTC, merged