[select] select doc update v11
carbon-design-system/carbon-website pull request #3282
Opened 2022-11-22 21:26 UTC by thyhmdo

Updated content and images for the [Select](https://carbondesignsystem.com/components/select/usage/) component.

2022-11-28 21:22 UTC, alisonjoseph approved these changes

2022-12-06 16:00 UTC, laurenmrice requested changes
Looking great Thy, sorry for my late review! Most of my review consists of some small content typos.

2022-12-06 16:00 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +The select component is used for collecting user-provided information from a
```suggestion
The select component collects user-provided information from a
```

2022-12-06 16:00 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +list of options. Selects are usually used in forms, where a user submits data
```suggestion
list of options. Selects are usually used in forms where a user submits data
```

2022-12-06 16:00 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +look similar, but they have different functions.
```suggestion
look similar, they have different functions.
```

2022-12-06 16:00 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +  item from that list. It works best in forms when users select an option from
```suggestion
  It works best in forms when users choose an option from
```

2022-12-06 16:00 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +  The example shows that the dropdown presents a list of options for actions
```suggestion
  Example of a dropdown list of actional options
```

2022-12-06 16:00 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +| _Enabled_   | When the select is live but a user is not directly interacting with it. This is commonly referred to as the default or normal state of the component. An enabled select field should co
```suggestion
| _Enabled_   | When the select is live and a user is not directly interacting with it. This is commonly referred to as the default or normal state of the component. An enabled select field should contain a default value.                                                |
```

2022-12-06 16:00 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +| _Skeleton_  | Used on an initial page load to indicate that the number input has not yet fully loaded.
```suggestion
| _Skeleton_  | Used on an initial page load to indicate that the select has not yet fully loaded.                                                                                                                                                                     |
```

2022-12-06 16:00 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +![Select interactive states](images/select-usage-9.png)
— I think you could remove the word `state` in the labels of each component in the image.
— The disabled state does not get a bottom-border rule.

2022-12-06 16:00 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +![Select keyboard interaction](images/select-usage-11.png)
I notice in the second part of this image you have the pink overlay on the field input, I don't think it's needed in this image.

2022-12-09 14:18 UTC, tw15egan approved these changes

2022-12-12 15:54 UTC, laurenmrice requested changes
@thyhmdo A couple small things Thy! Just saw some code errors happening in the content and a typo. Otherwise looks good!

2022-12-12 15:54 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +#### Select versus Dropdown
There are some weird code things going on here in the Select versus Dropdown section.
<img width="997" alt="Screen Shot 2022-12-12 at 10 48 37 AM" src="https://user-images.githubusercontent.com/43969356/207090145-912f941a-67c7-411e-9903-e2e624b5c3d2.png">

2022-12-12 15:54 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +## Formating
```suggestion
## Formatting
```

2022-12-12 15:54 UTC, laurenmrice commented on src/pages/components/select/usage.mdx
> +#### Keyboard
There is another code bug happening here.
<img width="1013" alt="Screen Shot 2022-12-12 at 10 52 53 AM" src="https://user-images.githubusercontent.com/43969356/207091145-ccf7d663-8d7c-4f2b-a9dc-02ee5dfbfb03.png">

2022-12-16 13:33 UTC, laurenmrice approved these changes
Looks great Thy! ⭐️

2022-12-16 15:06 UTC, merged