Docs: Fluid select
carbon-design-system/carbon-website pull request #3320
Opened 2022-12-21 15:54 UTC by laurenmrice

Closes #

- Docs for fluid select

#### Changelog

*Usage*
- Added a "Styling" section under Formatting to give an overview of Fixed and Fluid styles .
- Added `tab` component with Fluid image example to select images (not all have one).

*Style*
in progress

**Testing/Reviewing**
- Go to the "Select" page and proof read add fluid sections and images on usage and style tabs.

2023-01-05 15:44 UTC, thyhmdo commented
This looks great! There's only one thing:  
In the Anatomy, I wonder if the tooltip icon should be in a box spec instead of the. Also, for number 3, the text is still "Helper text" instead of the Tooltip. 

![image](https://user-images.githubusercontent.com/77697351/210820910-4d70823d-fed9-4b8e-979e-ef5491a95b07.png)

![image](https://user-images.githubusercontent.com/77697351/210821034-2fb05a1d-324a-492d-bfdf-54cf786372f9.png)

2023-01-05 17:28 UTC, aagonzales requested changes
- [x] Could you add the label to these fixed inputs in the sizing section. The label placement is the big differentiator when talking about fixed vs fluid. 

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/11670886/210842333-fe6d943a-78ce-45f7-96f7-2ff1d7872a3b.png">

- [x] Fluid error border should be 2px
<img width="426" alt="image" src="https://user-images.githubusercontent.com/11670886/210842628-de103094-6231-4fe3-8940-4feab999bd91.png">

- [x] Add a fixed/fluid tab to the first color section image on the style tab as well

2023-01-05 19:06 UTC, laurenmrice commented
Thanks @thyhmdo  and @aagonzales ! I made all of those updates. I changed the Fixed size image to be this below, it just is not showing up in the preview for some reason.

<img width="987" alt="Screen Shot 2023-01-05 at 2 05 32 PM" src="https://user-images.githubusercontent.com/43969356/210860497-e88694bc-4d4c-4248-8da3-0a10b77d80f5.png">

2023-01-05 19:10 UTC, aagonzales approved these changes

2023-01-06 18:18 UTC, thyhmdo approved these changes

2023-01-12 16:40 UTC, merged