Fluid form
carbon-design-system/carbon-website pull request #3356
Opened 2023-01-19 22:01 UTC by aagonzales

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2023-01-24 19:44 UTC, laurenmrice requested changes
Looks really good! ⭐️ Just a couple of typos in content/images.

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +![Anatomy of a fixed form](images/form-usage-1.png)
Anatomy image (fixed):
This abbreviation should be `etc.` not ect.
<img width="635" alt="Screen Shot 2023-01-24 at 12 44 54 PM" src="https://user-images.githubusercontent.com/43969356/214387590-3483733b-cdb4-4f2c-9496-03ada688817b.png">

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +![Anatomy of a fluid form](images/form-usage-1-fluid.png)
Anatomy image (fluid):
The spacing between the text and the icon should be 8px, but I think it's at 16px? 
<img width="443" alt="Screen Shot 2023-01-24 at 1 05 41 PM" src="https://user-images.githubusercontent.com/43969356/214387871-195d6967-1b25-44ca-adf7-85f76eeb621b.png">

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +information is need to assist the user in correctly completing a field, such as
```suggestion
information is needed to assist the user in correctly completing a field, such as
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +or references may also be include if needed. In certain situations where complex
```suggestion
or references may also be included if needed. In certain situations where complex
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +simply and directly as helper text under the field and not be in a tooltip
```suggestion
simply and directly as helper text under the field and not be in a tooltip.
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +Fluid inputs are an exception to the no critial information in tooltips rule.
```suggestion
Fluid inputs are an exception to the no critical information in tooltips rule.
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +space under the field needed for helper text. All assistive text wither
```suggestion
space under the field needed for helper text. All assistive text whether
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +pertinent or additional is provided through a tooltip when using fluid inputs.
```suggestion
pertinent or additional, is provided through a tooltip when using fluid inputs.
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +![Example of a fluid input using a tooltip for help](images/form-usage-7.png)
This image has a `etc.` typo as well.
<img width="551" alt="Screen Shot 2023-01-24 at 1 01 41 PM" src="https://user-images.githubusercontent.com/43969356/214388924-00cffaa8-6660-46b8-8b6c-ea3cf02d598f.png">

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +| [Free form inputs](/patterns/forms-pattern/#text-inputs)     | Free-form text inputs are the most commonly used components in forms. They allow a user to enter any configuration of a letters or num
```suggestion
| [Free form inputs](/patterns/forms-pattern/#text-inputs)     | Free-form text inputs are the most commonly used components in forms. They allow a user to enter any configuration of letters or numbers. Common free-form inputs include: text input and text area.              |
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +Carbon provides a variety of data input components that enable a user to make a
```suggestion
Carbon provides a variety of data input components that enable a user to
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +![Examples fluid input states](images/form-usage-states-fluid.png)
The warning helper text should be $text-primary in the fluid image.
<img width="364" alt="Screen Shot 2023-01-24 at 2 31 42 PM" src="https://user-images.githubusercontent.com/43969356/214390481-6763f3b6-5d94-44bd-abdd-e2e70dc6f307.png">

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +![Examples of fixed input states](images/form-usage-states-fixed.png)
The skeleton state input field needs to bottom align with the disabled field to the left of it in the fixed image.
<img width="829" alt="Screen Shot 2023-01-24 at 2 32 48 PM" src="https://user-images.githubusercontent.com/43969356/214390668-a3bf3063-fb0d-4a60-a8a2-e53f8e2e8615.png">

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +| [Buttons in forms](/patterns/forms-pattern/#buttons])                             | Provides guidance on button alignment, emphasis, placement and naming in relation to a form.                    |
```suggestion
| [Buttons in forms](/patterns/forms-pattern/#buttons])                             | Provides guidance on button alignment, emphasis, placement, and naming in relation to a form.                    |
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/usage.mdx
> +| [Form layout](/patterns/forms-pattern/#designing-a-form)                          | Additional guidance around layout, spacing, columns in a form.                                                  |
```suggestion
| [Form layout](/patterns/forms-pattern/#designing-a-form)                          | Additional guidance around layout, spacing, and columns in a form.                                                  |
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/style.mdx
> +| Title area           | margin-bottom | 40 / 2   | `$spacing-08` |
```suggestion
| Title area           | margin-bottom | 40 / 2.5   | `$spacing-08` |
```

2023-01-24 19:44 UTC, laurenmrice commented on src/pages/components/form/style.mdx
> +| Title area           | margin-bottom | 40 / 2   | `$spacing-08` |
```suggestion
| Title area           | margin-bottom | 40 / 2.5   | `$spacing-08` |
```

2023-01-24 20:06 UTC, aagonzales commented
Ok updates made, thanks of checking. I forgot to run it through Grammarly 😵‍💫

2023-01-24 20:53 UTC, laurenmrice approved these changes
🚀

2023-01-25 19:03 UTC, tw15egan approved these changes
Looks great 🎉

2023-01-25 19:19 UTC, merged