fix(react): replace codesandbox link with stackblitz
carbon-design-system/carbon-website pull request #3369
Opened 2023-01-26 15:37 UTC by tay1orjones

Thanks to @skcele for catching this!

#### Changelog

**Changed**

- replaced outdated codesandbox link with the stackblitz vite template link

**Testing / Reviewing**

- Go to `developing/frameworks/react/` on the deploy preview
- Validate the stackblitz resource link works and has the proper icon

2023-01-26 16:19 UTC, francinelucca requested changes
Icon is actually not loading for me, not sure why 🧐
<img width="904" alt="image" src="https://user-images.githubusercontent.com/40550942/214889791-50236b4d-e6c6-4efb-bf9f-1b4d441d85b9.png">

2023-01-27 16:41 UTC, francinelucca reviewed
I can see the icon now! it looks kind of big to me though 🤔, is this the correct size? 
<img width="985" alt="image" src="https://user-images.githubusercontent.com/40550942/215143212-5b96c4a4-1522-4f65-9ec2-45ab4405d5cc.png">

2023-01-27 17:05 UTC, tay1orjones commented
@francinelucca I think it's actually the storybook one that is too small - all the icons are within a container of 32x32, but the actual icon size varies. Some don't take up the full space

2023-01-27 17:16 UTC, francinelucca approved these changes

2023-01-31 22:25 UTC, aledavila approved these changes

2023-02-07 15:35 UTC, merged