docs(table): expansion and selection
carbon-design-system/carbon-website pull request #3445
Opened 2023-03-21 20:40 UTC by aagonzales

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2023-03-23 17:05 UTC, francinelucca requested changes
LGTM! one minor detail

2023-03-23 21:33 UTC, laurenmrice commented on src/pages/components/data-table/usage.mdx
> +_This content is accessible to IBMers only_
```suggestion
_This content is accessible to IBMers only._
```

2023-03-23 21:34 UTC, laurenmrice approved these changes
Just one punctuation comment. Everything else looks good to me ✅

2023-03-27 14:59 UTC, francinelucca approved these changes

2023-03-27 16:22 UTC, tay1orjones approved these changes

2023-03-27 16:31 UTC, merged