docs(content switcher): add icon-only variant
carbon-design-system/carbon-website pull request #3473
Opened 2023-03-31 20:22 UTC by aagonzales

Closes https://github.com/carbon-design-system/carbon/issues/12458

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2023-04-11 18:51 UTC, tay1orjones approved these changes
Looks awesome!

2023-04-17 17:28 UTC, alisonjoseph approved these changes
LGTM!

2023-04-19 17:04 UTC, laurenmrice requested changes
Looks awesome! Just a couple typo comments:

2023-04-19 17:04 UTC, laurenmrice commented on src/pages/components/content-switcher/usage.mdx
> +3. **Label:** Text label or iccon that describes the content view.
```suggestion
3. **Label:** Text label or icon that describes the content view.
```

2023-04-21 17:50 UTC, laurenmrice approved these changes

2023-04-21 18:03 UTC, merged