docs: add localized date content to date picker
carbon-design-system/carbon-website pull request #3561
Opened 2023-05-23 14:18 UTC by laurenmrice

Closes #3370 

- Added localized date content to the date picker usage documentation

**New**

- Image and bullet explaining localized date functionality.

2023-05-24 19:23 UTC, tw15egan commented on src/pages/components/date-picker/usage.mdx
> +  language of the calendar. Localizing static dates in the same UI is also
```suggestion
    The date picker utilizes [flatpickr](https://flatpickr.js.org/), which accepts `dateFormat` and `locale` props
  that allow you to change how the date is displayed and lets you change the
  language of the calendar. Localizing static dates in the same UI is also
```

2023-05-24 19:25 UTC, tw15egan commented on src/pages/components/date-picker/images/date-picker-usage-localized.png
Would `03/15/2019` and `15/03/2019` be too similar? I think the biggest use case of changing this would be to turn off "American" formatting. We could also show that you can render dashes instead of slashes i.e `2023-06-23`

2023-05-24 20:48 UTC, andreancardona approved these changes
other than TJ's comments looks good!

2023-05-31 15:24 UTC, laurenmrice commented on src/pages/components/date-picker/images/date-picker-usage-localized.png
Ahhh, yes. I can update to that.

2023-05-31 15:36 UTC, laurenmrice commented on src/pages/components/date-picker/images/date-picker-usage-localized.png
@tw15egan Updated!

2023-05-31 16:09 UTC, thyhmdo commented
Small thing. Can we add captions for these images or move the Label image closer to the sentence "When using a simple date input... helper text below the label."? They look almost the same and I was confused a little bit about their differences.

2023-05-31 16:16 UTC, laurenmrice commented
@thyhmdo yes, we can add captions

2023-05-31 16:42 UTC, aubrey-oneal commented on src/pages/components/date-picker/usage.mdx
>  - When using calendar picker the date format will be automated if the user
```suggestion
- When using the calendar picker, the date format will be automated if the user
```

2023-05-31 16:43 UTC, aubrey-oneal requested changes
Looks good. Just suggested small grammar updates (adding commas after introductory clauses).

2023-06-01 17:48 UTC, aubrey-oneal approved these changes
Looks good! 🚀

2023-06-01 18:44 UTC, tw15egan commented
@laurenmrice changes look great! Ready to merge?

2023-06-01 19:54 UTC, laurenmrice commented
@tw15egan yes!

2023-06-01 19:59 UTC, merged