docs: update figma content with theme file deprecation change
carbon-design-system/carbon-website pull request #3674
Opened 2023-08-02 18:20 UTC by laurenmrice

Closes #3644 

Updates content in various places on the website to reflect the deprecation of our Figma theme files. 

#### Changelog

**Changed**

- Content on the `Designing > Get started` page.
- Content and images on the `Designing > Design Kits (Figma tab)` page.
- Content on the `Migrating > Guide > Design tab` page.

**Removed**

- Some old images not being used.

2023-08-03 19:25 UTC, aagonzales requested changes
Looks good! Just one place where you missed a reference to the white theme on the Figma kit page in the caption here 
<img width="865" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/11670886/ff7b50e4-e13d-4aa7-954d-e9b4bf2e3ce5">

2023-08-03 19:28 UTC, laurenmrice commented
Ahh. Good catch, thank you!! @aagonzales

2023-08-03 19:46 UTC, aagonzales approved these changes

2023-08-04 14:35 UTC, alisonjoseph approved these changes

2023-08-04 15:12 UTC, andreancardona approved these changes

2023-08-04 16:12 UTC, merged