Update accessibility.mdx
carbon-design-system/carbon-website pull request #3685
Opened 2023-08-04 21:11 UTC by mbgower

First draft of new accessibility content (without images)

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2023-08-23 17:36 UTC, laurenmrice requested changes
Let me know if you need help with images for this PR.

2023-08-24 01:52 UTC, tay1orjones approved these changes
I'm not sure what's up with the preview but the images look good locally.

<img width="1728" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/3360588/c6fa6af0-186f-4ba1-82e8-5e79241ea673">

2023-08-24 12:00 UTC, guidari approved these changes

2023-08-24 20:51 UTC, laurenmrice requested changes
I have revised the images in the[ image box folder](https://ibm.ent.box.com/folder/223115679697)

2023-08-24 20:51 UTC, laurenmrice commented on src/pages/components/contained-list/accessibility.mdx
> +item is itself clickable or contains an action button (such as ‘delete’). It is
```suggestion
item is clickable or contains an action button (such as ‘delete’). It is
```

2023-08-25 14:34 UTC, mbgower commented
@laurenmrice images and editorial changes incorporated. Please review and approve

2023-08-28 17:39 UTC, laurenmrice approved these changes

2023-08-28 17:50 UTC, merged