fix(get-started): remove vanilla reference
carbon-design-system/carbon-website pull request #3692
Opened 2023-08-10 16:01 UTC by tay1orjones

2023-08-10 20:23 UTC, kingtraceyj requested changes

2023-08-10 20:23 UTC, kingtraceyj commented on src/pages/developing/get-started.mdx
>  The Carbon Design System is built React first, with official support for Web
```suggestion
The Carbon Design System is built React first with official support for Web
```
i don't think you need a comma here

2023-08-14 14:16 UTC, andreancardona approved these changes
Other than running`format` and Tracey's suggestion looks good!

2023-08-23 14:25 UTC, laurenmrice approved these changes

2023-08-30 18:57 UTC, merged