/designing/tutorials/ is broken (404)
carbon-design-system/carbon-website pull request #3699
Opened 2023-08-17 17:56 UTC by iamamansharma

url is broken - https://carbondesignsystem.com/designing/tutorials/ updated the url to - version 10 - https://v10.carbondesignsystem.com/designing/tutorials/

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2023-08-17 18:02 UTC, iamamansharma commented
I have read the DCO document and I hereby sign the DCO.

2023-08-21 12:53 UTC, tay1orjones requested changes
In this case I don't think we want to redirect users to the v10 version of the website. Keeping them on the current/v11 site would be preferred. 

This page doesn't exist anymore but we could use the getting started page instead.

2023-08-21 12:53 UTC, tay1orjones commented on src/pages/all-about-carbon/who-uses-carbon.mdx
> +- Check out [design tutorials](https://v10.carbondesignsystem.com/designing/tutorials/) to learn more about some
```suggestion
- Check out [design tutorials](/designing/get-started/) to learn more about some
```

2023-08-22 16:02 UTC, iamamansharma commented
@tay1orjones can you please review now?

2023-08-23 14:23 UTC, laurenmrice approved these changes

2023-08-28 13:54 UTC, merged