Roadmap
carbon-design-system/carbon-website pull request #3815
Opened 2023-11-21 22:09 UTC by sstrubberg

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2023-11-22 03:46 UTC, alisonjoseph commented
I like the transparency, I know we've done things like this in past and its quickly gotten out of date, that would be my only concern.

2023-11-22 12:40 UTC, guidari reviewed
Awesome docs @sstrubberg!  🚀

2023-11-22 12:40 UTC, guidari commented on src/pages/whats-happening/roadmap/index.mdx
> +  [accessibility tabs](https://github.com/carbon-design-system/carbon/issues/13521)
Is this right?
```suggestion
- updating our
  [accessibility tabs](https://github.com/carbon-design-system/carbon/issues/13521)
```

2023-11-27 15:59 UTC, aubrey-oneal requested changes
It's looking great! Two things I'd suggest editing:
- Capitalize each bullet point. 
- Unfortunately we should probably take out Jeremy Caine's name and Linked In -- We probably would need him to sign a waver. And the waver we had internal IBM folks sign was limited to using their name on the contribution page only.

2023-11-28 22:45 UTC, sstrubberg commented
> I like the transparency, I know we've done things like this in past and its quickly gotten out of date, that would be my only concern.

I plan to maintain it myself in the same way I'm maintaining the Contribution section on the site.

2023-12-07 17:01 UTC, closed without merging