[Selectable Components: Structured List - Style] Website Doc
carbon-design-system/carbon-website pull request #3965
Opened 2024-03-11 11:32 UTC by Kritvi-bhatia17

Closes [#15775](https://github.com/carbon-design-system/carbon/issues/15775)

## New

**_Color_** & **_Interactive states_** section
> - [x] Added an image for both Transparent and Background structured list (enabled states)
> - [x] Added the color specs for structured list with background as 'optional'

**_Structure_** section
> - [x] Add _Default structure_ & _Selectable structure_ sections with description and images each

> - [x] Add a new section(_Size_ section) with description and images each

## Changed

**_Color_**, **_Interactive states_** & **_Structure_** section
> - [x] Updated the table have the correct color tokens

2024-03-11 14:32 UTC, tw15egan approved these changes
LGTM 👍 ✅

2024-03-14 15:54 UTC, laurenmrice requested changes
Looking good Kritvi! Just some comments below: 

**Structure section**
Since you are showing the hang and flush structured list specs in the image, the table above it also needs to have some information for the flush list specs. The table currently only has information for the hang structured list specs.

I would also add specs to the table for the Icon left and right padding.

2024-03-14 15:57 UTC, laurenmrice commented on src/pages/components/structured-list/style.mdx
> +![Sizes of structured list with selection](images/structured-list-style-7.png)
This image in the Size section could be simplified a bit with the specs, to direct the users attention more to the specifications of what changes between the condensed and default  heights. I will create an example of what I mean in your figma file.

2024-03-18 09:36 UTC, Kritvi-bhatia17 reviewed
.

2024-03-21 12:38 UTC, laurenmrice commented
Looks good Kritvi! I think after these small image bugs, it should be good to go!

I would check the bottom and top spacing in these areas in red in the following images (for both background and transparent images) to make sure they are the same size and that the component is centered in the center of the space. I can't tell if its the tab component in gatsby that is causing this, or if its in the actual image file.

<img width="834" alt="Screenshot 2024-03-21 at 8 26 39 AM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/1095c0b0-6ed6-46e1-a2f5-9e6a024ba832">

<img width="841" alt="Screenshot 2024-03-21 at 8 30 57 AM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/88f820c8-5791-43db-85bb-e089eaae5a1f">

------

This image just needs to bring this top divider in, its too long.
<img width="1121" alt="Screenshot 2024-03-21 at 8 33 12 AM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/a6a3ddd7-8ce0-41f2-b583-a1b49540f78e">

2024-03-25 08:06 UTC, Kritvi-bhatia17 commented
> Looks good Kritvi! I think after these small image bugs, it should be good to go!
> 
> I would check the bottom and top spacing in these areas in red in the following images (for both background and transparent images) to make sure they are the same size and that the component is centered in the center of the space. I can't tell if its the tab component in gatsby that is causing this, or if its in the actual image file.
> 
> <img alt="Screenshot 2024-03-21 at 8 26 39 AM" width="834" src="https://private-user-images.githubusercontent.com/43969356/315291606-1095c0b0-6ed6-46e1-a2f5-9e6a024ba832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTM0NTYsIm5iZiI6MTcxMTM1MzE1NiwicGF0aCI6Ii80Mzk2OTM1Ni8zMTUyOTE2MDYtMTA5NWMwYjAtNmVkNi00NmUxLWEyZjUtOWU2YTAyNGJhODMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3NTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMmQwOGNlYjIwMTI5OWQwYzNkZjIyMjg1OGM2OTcyODkyZGE3YWMwMzcwNWE1NmY5MzljMWJmMGFmYTZiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U9fViAzvYKPEeqZ8mnlmS4clTv20cvxJ9CFujljWoQQ"> <img alt="Screenshot 2024-03-21 at 8 30 57 AM" width="841" src="https://private-user-images.githubusercontent.com/43969356/315291617-88f820c8-5791-43db-85bb-e089eaae5a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTM0NTYsIm5iZiI6MTcxMTM1MzE1NiwicGF0aCI6Ii80Mzk2OTM1Ni8zMTUyOTE2MTctODhmODIwYzgtNTc5MS00M2RiLTg1YmItZTA4OWVhYWU1YTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3NTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYTE3N2UwNTM5ZmU4MTJjMmMzOWQ5MWRhMjI4ZjdmMTZmNDEzYTBiM2NmMzMxOTFiZDI1N2E1ODM2M2VlNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q1aPu-LASl7GQSQMhDFkttz2uyP-wwXNUfNRbir_F9Q">
> This image just needs to bring this top divider in, its too long. <img alt="Screenshot 2024-03-21 at 8 33 12 AM" width="1121" src="https://private-user-images.githubusercontent.com/43969356/315292159-a6a3ddd7-8ce0-41f2-b583-a1b49540f78e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTM0NTYsIm5iZiI6MTcxMTM1MzE1NiwicGF0aCI6Ii80Mzk2OTM1Ni8zMTUyOTIxNTktYTZhM2RkZDctOGNlMC00MWYyLWI1ODMtYTFiNDk1NDBmNzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3NTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZDMwNWEzZjVlODk1MTAyZTA0ZDhlNGIwOGM0M2Q0MDcwYmQ4YmZhMmE0YTM1ODdkZTcyYTIyM2NkY2YzYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JWv_TqqsIIDA5BtXKMvhQi-MFlVteUkRsQ2wxKldF4c">

Hi Lauren!
Oh damn, thank you for checking. Here are a couple of points:

- The preview link isn't showing the latest update for some reason.
- While the images have the corrected spacing, there seems to be an issue with the code introducing a tab above it, causing unequal spacing top and bottom. I'm not sure if it's a code issue, but the images in Figma have the correct spacing. I think I might need to connect with one of the developers to address this.
- Regarding the last image you pointed out, if you check under [files changed](https://github.com/carbon-design-system/carbon-website/pull/3965/files#diff-e8788555405bb6e0491639f3f59e01fc8fef304c0636de505599028c070b2593), it appears to be correct there, but it's not reflecting correctly on the preview link provided.

Thanks again!

2024-03-25 11:57 UTC, laurenmrice approved these changes

2024-03-28 17:14 UTC, Kritvi-bhatia17 commented
> Looks good Kritvi! I think after these small image bugs, it should be good to go!
> 
> I would check the bottom and top spacing in these areas in red in the following images (for both background and transparent images) to make sure they are the same size and that the component is centered in the center of the space. I can't tell if its the tab component in gatsby that is causing this, or if its in the actual image file.
> 
> <img alt="Screenshot 2024-03-21 at 8 26 39 AM" width="834" src="https://private-user-images.githubusercontent.com/43969356/315291606-1095c0b0-6ed6-46e1-a2f5-9e6a024ba832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDU4NDMsIm5iZiI6MTcxMTY0NTU0MywicGF0aCI6Ii80Mzk2OTM1Ni8zMTUyOTE2MDYtMTA5NWMwYjAtNmVkNi00NmUxLWEyZjUtOWU2YTAyNGJhODMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE3MDU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4Njc0MWQ0N2NhOTFhZTY3YzVhYWZlNmFmNzc2MDliZjE1ZTI4ODM2MTA2OTEyMjE5ODAxM2FkMjdiNDRjYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cC9aoS3dcaxV6wQj3-0UlbCKmvQ1aOEiMVoapjCgq5c"> <img alt="Screenshot 2024-03-21 at 8 30 57 AM" width="841" src="https://private-user-images.githubusercontent.com/43969356/315291617-88f820c8-5791-43db-85bb-e089eaae5a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDU4NDMsIm5iZiI6MTcxMTY0NTU0MywicGF0aCI6Ii80Mzk2OTM1Ni8zMTUyOTE2MTctODhmODIwYzgtNTc5MS00M2RiLTg1YmItZTA4OWVhYWU1YTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE3MDU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNWI4YjQ1YzNlNDgyNjAyMzliN2Q4OGJmOGMzNzIwMDk4MGY0N2YwZDVjZTE0Y2MwN2UxNGM0NmI0MzI1NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bQs2RTX018F4Su_aMTHXBJy7QRcKAiYdJ4a1aG7i4T0">
> This image just needs to bring this top divider in, its too long. <img alt="Screenshot 2024-03-21 at 8 33 12 AM" width="1121" src="https://private-user-images.githubusercontent.com/43969356/315292159-a6a3ddd7-8ce0-41f2-b583-a1b49540f78e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDU4NDMsIm5iZiI6MTcxMTY0NTU0MywicGF0aCI6Ii80Mzk2OTM1Ni8zMTUyOTIxNTktYTZhM2RkZDctOGNlMC00MWYyLWI1ODMtYTFiNDk1NDBmNzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE3MDU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MjQzNTQxMmMzMzdmMWJmZTRiODM0OWQ3ZGEzN2M1Y2M3OTczZTA2ODU3OTA2OTViYTQ4NjAwYTQwMjc0MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K4vG8RCLDASJ0ImtKVYgLR-MTB7STl3pe2Cv_FStlL0">


Hi @laurenmrice! I spoke with @tay1orjones to clarify a couple of points:
1. Regarding the padding issue, I've raised [an issue](https://github.com/carbon-design-system/carbon-website/issues/3987#issue-2213719797) after discussing with @tay1orjones. There seems to be unequal padding set in the code, and we might need to discuss it with the team.
2. The preview link has been updated, and it now displays the latest images.

The padding issue might take some time to resolve. In the meantime, I'll go ahead and `merge this PR`. Just wanted to keep you in the loop!

2024-04-28 07:33 UTC, merged