fix: Enhancement in color page token
carbon-design-system/carbon-website pull request #4211
Opened 2024-08-22 12:58 UTC by riddhybansal

Closes #4110 

Color Page Enhancements

#### Changelog

**New**

-Multiple H2 sections for Core, Component, and AI tokens
-Adding H3 anchor links inline with the H3 token headers in tables.
-Adding H3 mini-anchor link sections for easier navigation.
-Addition of a table under component tokens called "notification"

2024-08-27 09:27 UTC, riddhybansal commented
Hey reviewer , Please review the notification table and there hex code as this is newly added. Please verify 2 links added in the the description of component tokens and ai tokens are correct or not. Please check if the tokens are correctly categorised and navigating to the correct table.

2024-08-27 15:39 UTC, aagonzales commented on src/pages/elements/color/tokens.mdx
> +<AnchorLink>Background</AnchorLink>
These anchor links under the H2 sections are coming in at the larger size. Can we make them smaller like the anchor link on the [2x Grid](https://carbondesignsystem.com/elements/2x-grid/overview/#2x-grid-fundamentals) page?

2024-08-27 15:39 UTC, aagonzales commented on src/pages/elements/color/tokens.mdx
> +
There is a weird line break here: 
<img width="835" alt="image" src="https://github.com/user-attachments/assets/888296aa-d8e9-4d34-beb8-b5aa1b4e6bf4">

2024-08-27 15:39 UTC, aagonzales commented on src/pages/elements/color/tokens.mdx
> +
There is a weird gap here 
<img width="781" alt="image" src="https://github.com/user-attachments/assets/64d03ad5-ac10-4e71-8bba-eeecc49ac4b2">

2024-08-27 17:07 UTC, alisonjoseph commented on src/pages/elements/color/tokens.mdx
> +</a> for more information.
Should be able to switch this to markdown syntax to fix the line break vs html. 
`[developer documentation](https://github.com/carbon-design-system/carbon/blob/main/packages/styles/docs/sass.md#component-tokens)`

2024-08-27 17:08 UTC, alisonjoseph commented on src/pages/elements/color/tokens.mdx
> +<AnchorLinks>
```suggestion
<AnchorLinks small>
```

2024-08-28 19:48 UTC, aagonzales approved these changes
Looks good to me!

2024-08-29 13:54 UTC, alisonjoseph requested changes
Couple super minor copy edits, but this looks great! 🔥

2024-08-29 13:54 UTC, alisonjoseph commented on src/pages/elements/color/tokens.mdx
> +For more information on how to use the AI token, see the
```suggestion
For more information on how to use the AI tokens, see the
```

2024-08-29 13:54 UTC, alisonjoseph commented on src/pages/elements/color/tokens.mdx
> +[developer documentation](https://github.com/carbon-design-system/carbon/blob/main/packages/styles/docs/sass.md#component-tokens)
```suggestion
other than their own component. For more information on how to use component tokens, see the
[developer documentation](https://github.com/carbon-design-system/carbon/blob/main/packages/styles/docs/sass.md#component-tokens).
```

2024-08-29 14:52 UTC, riddhybansal commented
> Couple super minor copy edits, but this looks great! 🔥

OOPs small ones :(

2024-09-03 17:09 UTC, alisonjoseph approved these changes
LGTM! I think you just need to run `yarn format` to get CI to pass

2024-09-04 19:50 UTC, merged