Menu accessibility tab doc update
carbon-design-system/carbon-website pull request #4250
Opened 2024-09-10 12:00 UTC by alina-jacob

Closes https://github.com/carbon-design-system/carbon-website/issues/3796

2024-09-11 18:22 UTC, ariellalgilmore commented on src/pages/components/menu/accessibility.mdx
> +Row>
```suggestion
<Row>
```

2024-09-13 13:39 UTC, alisonjoseph approved these changes

2024-09-13 14:30 UTC, laurenmrice requested changes
Looking good Alina! Left a couple comments below:

2024-09-13 14:30 UTC, laurenmrice commented on src/pages/components/menu/accessibility.mdx
> +The menu is reached by tab. When the menu is open, the first item takes focus.
```suggestion
The menu is reached by `Tab`. When the menu is open, the first item takes focus.
```

2024-09-16 11:32 UTC, Kritvi-bhatia17 approved these changes
Great work Alina! LGTM 🚀

If you have any research or iterations documented in a Figma file or Box note, could you please share them in the [issue's comments](https://github.com/carbon-design-system/carbon-website/issues/3796) (like this:)

<img width="913" alt="image" src="https://github.com/user-attachments/assets/d7c21a3d-143c-4504-a01d-075ebd2fafd5">

2024-09-18 19:50 UTC, laurenmrice commented on src/pages/components/menu/accessibility.mdx
> +opened and closed using the right and left arrow key respectively. When the menu or
```suggestion
opened and closed using the right and left arrow keys respectively. When the menu or 
```

2024-09-18 19:52 UTC, laurenmrice commented on src/pages/components/menu/accessibility.mdx
> +![example of menu keyboard interaction](images/accessibility-menu-2.png)
I have left a comment in your Figma file about this image.

2024-09-19 17:10 UTC, laurenmrice approved these changes

2024-09-23 16:22 UTC, tay1orjones approved these changes

2024-09-23 17:09 UTC, merged