[Status indicator] Update Status indicator pattern guidance
carbon-design-system/carbon-website pull request #4309
Opened 2024-10-03 18:19 UTC by thyhmdo

Closes #https://github.com/carbon-design-system/carbon-website/issues/4272 and https://github.com/carbon-design-system/carbon-website/issues/4050

------

Figma file review: https://www.figma.com/design/EqKmxlJmBiEB4yPBKpGlrZ/Status-Indicator-(Pattern)?node-id=1-1365

### New
- Variant table
- Icon vs Shape indicator

### Changelog
- Structure in general
- Icon indicator table in its variant
- Removed a few icon indicators in the table
- Removed one shape indicator in the table
- Other general guidance on labeling, type pairing, and accessibility

2024-10-04 14:15 UTC, alisonjoseph commented
The not started light image isn't displaying, I think the file might be missing.

<img width="535" alt="Screenshot 2024-10-04 at 9 14 29 AM" src="https://github.com/user-attachments/assets/849128ac-a148-4fb2-89f3-f08131c242a7">

2024-10-04 20:32 UTC, aagonzales reviewed
Wow, awesome work Thy! I left a few formatting suggestions here in the PR and also some other general comments and questions over in Figma.

2024-10-04 20:32 UTC, aagonzales commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +Icon indicators, also known as ‘contextual’ status indicators, are linked to
I don't think the single quote is right here for contextual, it should be either: 
- `contextual` (code snippet)
- "contextual" (double quote)

2024-10-04 20:32 UTC, aagonzales commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +  *Differential indicators must have either a ‘+’ or ‘-’ sign, a caret, or an
I think its supposed to be double quotes here not single. 
```suggestion
  *Differential indicators must have either a “+” or “-” sign, a caret, or an
```

2024-10-04 20:32 UTC, aagonzales commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +especially for users with color vision deficiencies. While color can be useful,
Formatting suggestion

```suggestion
Relying solely on color to convey status is insufficient,
especially for users with color vision deficiencies (refer to [Use of Color](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html)). While color can be useful,
```

2024-10-04 20:32 UTC, aagonzales commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +[Non-text Contrast](https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast),
```suggestion
it must be paired with text or other visual cues. To meet accessibility
standards, and to pass
[non-text contrast](https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast),
```

2024-10-14 18:58 UTC, alisonjoseph commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +recommended to use 14pt or 12pt in smaller spaces or when used as a secondary
Should this be px instead of pt?

2024-10-14 18:59 UTC, alisonjoseph approved these changes
This LGTM other than one comment around using px instead of pt when referring to font sizes.

2024-10-14 21:40 UTC, aagonzales reviewed
Just some small things still

2024-10-14 21:40 UTC, aagonzales commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +Color is optional in these situations as long as the value has either a "+" or
The quotes here are coming in correctly here.
<img width="100" alt="image" src="https://github.com/user-attachments/assets/7a20f875-b078-4e7a-a046-94a9a418a767">

2024-10-14 21:40 UTC, aagonzales commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +If your product needs an icon that’s not currently included, please reach out to
Can we say open an issue instead here and link them to the correct repo?

2024-10-14 21:40 UTC, aagonzales commented on src/pages/patterns/status-indicator-pattern/index.mdx
>  This palette is only for added contrast accessibility when using yellows and
I think we should still say these colors are not part of the _brand_ palette and should not be used in other contexts.

2024-10-17 14:39 UTC, thyhmdo commented
Alina's feedback: 

An image will help improve this context 

![image](https://github.com/user-attachments/assets/7219ade9-aec5-422c-96d0-e75df42558fc)

----

Taylor's feedback 
- Adding a fill behind some icons would work (like how other Warning and Failed states are being implemented right now)
```
.#{$prefix}--text-input__invalid-icon--warning {
    fill: $support-warning;
  }

```

Slight difference there is for the inputs we always set background-color: $field; whereas with standalone status icons we won't know/control what background they're placed on.
We could scope the selectors to set specific fill on each layer though, in addition to the $background

2024-10-18 13:22 UTC, laurenmrice requested changes
This looks really great, @thyhmdo ! Just a couple of minor things. Great work! ⭐️

- [x] The square border around the icons/symbols should be `Magenta 60` to match the line that connects to it. 

<img width="712" alt="Screenshot 2024-10-18 at 8 35 33 AM" src="https://github.com/user-attachments/assets/6c94db2d-638c-4fa8-8738-d38ddacfca01">

---

- [x]This image under the Shape indicator section needs to be updated to show the correct colors for the indicators in the data table. Right now they all look orange.
  - Note: This has been corrected, the correct image asset is in here, its just not updating in the preview.

<img width="820" alt="Screenshot 2024-10-18 at 8 55 44 AM" src="https://github.com/user-attachments/assets/ab48e805-5834-4cdc-aa3f-80e00de60895">

---

- I think this column header for this section should say "Shape" instead of "Icon"?

<img width="512" alt="Screenshot 2024-10-18 at 8 57 56 AM" src="https://github.com/user-attachments/assets/095520af-3139-4cd3-a7c9-44fd77eb07e0">

---

- I noticed that in the [Shape indicator table](https://carbondesignsystem-git-fork-thyhmdo-de4bbb-carbon-design-system.vercel.app/patterns/status-indicator-pattern/#shape-indicator-severity-levels) you use slashes to separate different tokens per shape, but in the [Icon indicator table](https://carbondesignsystem-git-fork-thyhmdo-de4bbb-carbon-design-system.vercel.app/patterns/status-indicator-pattern/#icon-indicator-severity-levels) you use commas. I would just pick one approach for consistency, maybe just use the comma?

2024-10-18 13:22 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +#### Best practice
```suggestion
#### Best practices
```

2024-10-18 13:22 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +#### Best practice
I know there is one thing under this section right now, but we usually keep this heading plural and there could be more best practices to add in the future.

2024-10-18 13:22 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +<Caption>Badges with numbers range from one to three digits</Caption>
```suggestion
<Caption>Badges with numbers ranging from one to three digits</Caption>
```

2024-10-18 13:22 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +The badge without number is commonly seen in toolbars' icon buttons.
```suggestion
The badge without a number is commonly seen in toolbars' icon buttons.
```

2024-10-18 13:22 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +meet accessibility standards, and to pass
```suggestion
meet accessibility standards and to pass
```

2024-10-18 13:22 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +Using symbols alone is acceptable, as long as they meet non-text contrast
```suggestion
Using symbols alone is acceptable as long as they meet non-text contrast
```

2024-10-18 13:22 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +  Example shows the icon indicators do not need outlines while icon indicators
```suggestion
  Example shows the icon indicators do not need outlines, while icon indicators
```

2025-01-08 20:43 UTC, aagonzales commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +| [Shape indicator](#shape-indicator)                  | Useful in smaller spaces or when users need to scan large amount of data.
These comments still look unresolved. @thyhmdo

2025-01-08 20:52 UTC, aagonzales commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +The badge without number is commonly seen in toolbars' icon buttons.
@thyhmdo this might just be something weird with the preview because I don't see it like this in the markdown but there's something weird happening with the text this section. 
<img width="842" alt="image" src="https://github.com/user-attachments/assets/461c6b46-b733-483c-bd58-5f5bcb018d9e" />

2025-01-10 19:23 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +The badge without number is commonly seen in toolbars' icon buttons.
@thyhmdo I also still see what Anna is saying above.

2025-01-10 19:26 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +  Example shows the icon indicators do not need outlines while icon indicators
@thyhmdo I actually think this caption means to say the following: 

> "Example shows icon indicators do not need outlines, while shape indicators do due to the lack of symbols."

2025-01-10 19:57 UTC, laurenmrice requested changes

2025-01-10 19:57 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +### Elements
> As a result, status indicators should rely on at least two elements: color, shape, or symbol. 

I think this means to say: "As a result, status indicators should rely on at least two of the following elements: color, shape, or symbol."

2025-01-10 19:57 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +<StatusIndicatorTable attention="high" />
Since we are showing color tokens now instead of color values, I think we should make them inline code snippets like we do on the style tabs. This should also be done in the Shape indicator statuses table.

2025-01-10 19:57 UTC, laurenmrice commented on src/pages/patterns/status-indicator-pattern/index.mdx
> +### Shape indicator statuses
Use a comma in this table instead of a slash when separating multiple color tokens like you do in the Icon indicator statuses table for consistency.

2025-03-12 19:15 UTC, laurenmrice approved these changes
The pattern docs look good to me! ⭐️ 🎉

Note: I am going to open a separate bug issue though about the code snippets in the table. They are clickable and also create a focus border in the row, which shouldn’t be appear. The inline code snippets should be following the same color and read-only interaction as the ones on our Style tab tables, but it seems more like a Gatsby theme bug problem.

2025-03-13 16:51 UTC, aagonzales approved these changes
It looks good to me! Great job @thyhmdo !! Let's ship it.

2025-03-13 17:41 UTC, laurenmrice commented
@kennylam When you get some time, could you help with this merge conflict?

2025-03-17 15:45 UTC, merged