feat: Updated feature flag links
carbon-design-system/carbon-website pull request #4330
Opened 2024-10-21 18:30 UTC by guidari

Closes https://github.com/carbon-design-system/carbon/issues/17821

Updated links to match this [PR](https://github.com/carbon-design-system/carbon/pull/17806)

2024-10-24 12:52 UTC, alina-jacob requested changes
Hi @guidari, this looks good! 🚀 
Not sure if this is relevant to the current PR, so ignore if irrelevant.

1. [Treeview](https://deploy-preview-17806--v11-carbon-react.netlify.app/?path=/story/components-treeview-feature-flag--playground) is the only component which has the playground first and the feature flag overview later. All other feature flag folders have overview first and the story later. 
<img width="298" alt="image" src="https://github.com/user-attachments/assets/c1e064f4-024f-4813-bc9e-027a5354ddc4">

<br>

2. The [nested overflow menu](https://deploy-preview-17806--v11-carbon-react.netlify.app/?path=/story/components-overflowmenu-feature-flag--nested) works a little odd in this PR, it seems to be working alright in our [current storybook](https://react.carbondesignsystem.com/?path=/story/experimental-feature-flags-overflowmenu--nested)!

2024-10-25 07:30 UTC, Kritvi-bhatia17 commented on src/pages/help/faq/index.mdx
The updated URL isn’t working, but the original intention behind adding the feature flag link under the Experimental section was that it used to be the first item there. Now that we’ve moved the feature flag section above, according to the latest Storybook, we could add the Fluid component [link](https://react.carbondesignsystem.com/?path=/docs/experimental-fluid-components-fluidform--overview). Alternatively, if there’s another link that could direct users to the Experimental section, we could use that instead.

2024-10-25 14:09 UTC, guidari commented on src/pages/help/faq/index.mdx
Not sure I understand what you mean here. Sorry

2024-10-25 14:21 UTC, guidari commented
> Hi @guidari, this looks good! 🚀 Not sure if this is relevant to the current PR, so ignore if irrelevant.
> 
> 1. [Treeview](https://deploy-preview-17806--v11-carbon-react.netlify.app/?path=/story/components-treeview-feature-flag--playground) is the only component which has the playground first and the feature flag overview later. All other feature flag folders have overview first and the story later.

Interesting... I'm not sure why it is like that on the repo 🤔

2024-10-25 14:31 UTC, alina-jacob approved these changes

2024-10-25 14:37 UTC, Kritvi-bhatia17 commented on src/pages/help/faq/index.mdx
No worries! I was just mentioning that this FAQ is intended to link to the Experimental section in Storybook. Previously, the feature flag section was the first item under Experimental, but now that it’s been moved, we could instead link to the [FluidForm overview page](https://react.carbondesignsystem.com/?path=/docs/experimental-fluid-components-fluidform--overview) within the Fluid components section.

<img width="307" alt="image" src="https://github.com/user-attachments/assets/beeb1aad-bb7a-44bc-825c-333e27393750">

2024-11-07 21:24 UTC, merged