fix: Updated the Dropdown component's Usage tab to address a11y comments
carbon-design-system/carbon-website pull request #4346
Opened 2024-10-31 12:50 UTC by Kritvi-bhatia17

Closes #3526 

This PR updates the Dropdown component Usage tab to incorporate comments from the referenced issue. Additionally, the content on the Usage tab has been aligned with the latest focus state discussion.

#### Changelog

**Changed**

- Content within several sections has been updated to address the comments (Ref: [Figma file](https://www.figma.com/design/xHzG8VCEAXXJnV0GAzcj44/Dropdown?node-id=5-64094&t=4aMoth3WRkE9kGmj-4)).
- Updated the images with latest focus state discussion.

2024-10-31 17:06 UTC, laurenmrice requested changes
Only a couple small changes!

2024-11-01 17:04 UTC, mbgower commented on src/pages/components/dropdown/usage.mdx
>  - By default, the dropdown displays placeholder text in the field when closed.
This sorta reads like there is always placeholder text, which has already been listed above as optional. How about...
```suggestion
- By default, the dropdown displays any placeholder text in the field when closed.
```

2024-11-06 12:51 UTC, laurenmrice requested changes
@Kritvi-bhatia17 
- The AI images (default/fluid) on the Usage tab seem to still have the top border turned on under the focus state. They should be off.
- In the content section, for the part about the carbon tooltip on ellipses option text, we currently do not show it this way in code; instead, we show a browser-based tooltip. This should be a separate design issue that we need to come to a decision on to have more consistency across our components with how we treat ellipses on text. If a carbon tooltip is the desired design from a11y, we can look into that. Since we don't show this in code right now for dropdowns, I would remove it from these docs for now because we want to show information here that is currently 1:1 with code.

2024-11-07 13:05 UTC, laurenmrice approved these changes

2024-11-11 06:04 UTC, Kritvi-bhatia17 commented
Hi @mbgower, @tay1orjones, @ariellalgilmore!
Could you please review this PR when you have a moment? Thanks!

2024-11-13 15:20 UTC, tay1orjones approved these changes
LGTM!

2024-11-15 09:26 UTC, Kritvi-bhatia17 commented
Hi @mbgower, could you please review this PR? Thanks!

2024-11-18 15:39 UTC, merged