[Inline loading] Updated text size and states
carbon-design-system/carbon-website pull request #4374
Opened 2024-11-21 20:43 UTC by thyhmdo

Closes #https://github.com/orgs/carbon-design-system/projects/39/views/13?filterQuery=sprint%3A%22%40next%22+design&pane=issue&itemId=80437243&issue=carbon-design-system%7Ccarbon-website%7C4271

**New**

- Updated the text size to 14pt 
- Updated the inactive state (to match with the code)

2024-11-25 17:38 UTC, laurenmrice requested changes
- This image needs the borders on the edges so the background doesn't blend in with the website page background.

<img width="835" alt="Screenshot 2024-11-25 at 12 33 24 PM" src="https://github.com/user-attachments/assets/e642ac37-9f9d-475c-9ee9-b6df7e9e822f">

----

- Could you try to vertically align the labels of these and visually center them within each section? Would be good to update the Style image to this too.
- The divider borders look like they are two different colors. They should be the border-subtle-01 color for the gray 10 theme. 

<img width="773" alt="Screenshot 2024-11-25 at 12 34 24 PM" src="https://github.com/user-attachments/assets/3fed3fc9-6219-4e1a-af20-e442295455b9">

----
- The inline loading label should be $body-compact-01.
<img width="833" alt="Screenshot 2024-11-25 at 12 36 28 PM" src="https://github.com/user-attachments/assets/a7285b88-fc56-4fd6-858a-61f513fa8ab4">

2024-12-04 12:15 UTC, guidari approved these changes

2024-12-04 23:07 UTC, laurenmrice requested changes
Hey @thyhmdo ! The dividers here need to be the $border-subtle-01 in the Gray 10 theme.  Right now they are using the White theme and are a bit dark. It should be changed on both the Usage and Style tab. Other than that it looks good!

<img width="810" alt="Screenshot 2024-12-04 at 6 07 39 PM" src="https://github.com/user-attachments/assets/28fc5e79-0b97-4aa2-aab3-a0cc66e3a6b5">

2024-12-06 16:42 UTC, laurenmrice approved these changes

2024-12-06 16:53 UTC, merged